/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateProjectFromAsanaTemplateRequestAllOf1Workspace from './CreateProjectFromAsanaTemplateRequestAllOf1Workspace';

/**
 * The CreateProjectFromAsanaTemplateRequestAllOf1 model module.
 * @module model/CreateProjectFromAsanaTemplateRequestAllOf1
 * @version 1.0.4
 */
class CreateProjectFromAsanaTemplateRequestAllOf1 {
    /**
     * Constructs a new <code>CreateProjectFromAsanaTemplateRequestAllOf1</code>.
     * @alias module:model/CreateProjectFromAsanaTemplateRequestAllOf1
     */
    constructor() { 
        
        CreateProjectFromAsanaTemplateRequestAllOf1.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateProjectFromAsanaTemplateRequestAllOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateProjectFromAsanaTemplateRequestAllOf1} obj Optional instance to populate.
     * @return {module:model/CreateProjectFromAsanaTemplateRequestAllOf1} The populated <code>CreateProjectFromAsanaTemplateRequestAllOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProjectFromAsanaTemplateRequestAllOf1();

            if (data.hasOwnProperty('team')) {
                obj['team'] = ApiClient.convertToType(data['team'], 'String');
            }
            if (data.hasOwnProperty('workspace')) {
                obj['workspace'] = CreateProjectFromAsanaTemplateRequestAllOf1Workspace.constructFromObject(data['workspace']);
            }
            if (data.hasOwnProperty('project_template')) {
                obj['project_template'] = ApiClient.convertToType(data['project_template'], 'String');
            }
        }
        return obj;
    }


}

/**
 * *Create-only*. The team that this project is shared with. This field only exists for projects in organizations.
 * @member {String} team
 */
CreateProjectFromAsanaTemplateRequestAllOf1.prototype['team'] = undefined;

/**
 * @member {module:model/CreateProjectFromAsanaTemplateRequestAllOf1Workspace} workspace
 */
CreateProjectFromAsanaTemplateRequestAllOf1.prototype['workspace'] = undefined;

/**
 * The string ID of the Asana-created template to create the project from.
 * @member {String} project_template
 */
CreateProjectFromAsanaTemplateRequestAllOf1.prototype['project_template'] = undefined;






export default CreateProjectFromAsanaTemplateRequestAllOf1;

