/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldBaseAllOf from './CustomFieldBaseAllOf';
import CustomFieldCompact from './CustomFieldCompact';
import CustomFieldCompactAllOfDateValue from './CustomFieldCompactAllOfDateValue';
import EnumOption from './EnumOption';

/**
 * The CustomFieldBase model module.
 * @module model/CustomFieldBase
 * @version 1.0.1
 */
class CustomFieldBase {
    /**
     * Constructs a new <code>CustomFieldBase</code>.
     * @alias module:model/CustomFieldBase
     * @implements module:model/CustomFieldCompact
     * @implements module:model/CustomFieldBaseAllOf
     */
    constructor() { 
        CustomFieldCompact.initialize(this);CustomFieldBaseAllOf.initialize(this);
        CustomFieldBase.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldBase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldBase} obj Optional instance to populate.
     * @return {module:model/CustomFieldBase} The populated <code>CustomFieldBase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldBase();
            CustomFieldCompact.constructFromObject(data, obj);
            CustomFieldBaseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('resource_subtype')) {
                obj['resource_subtype'] = ApiClient.convertToType(data['resource_subtype'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('enum_options')) {
                obj['enum_options'] = ApiClient.convertToType(data['enum_options'], [EnumOption]);
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('date_value')) {
                obj['date_value'] = CustomFieldCompactAllOfDateValue.constructFromObject(data['date_value']);
            }
            if (data.hasOwnProperty('enum_value')) {
                obj['enum_value'] = ApiClient.convertToType(data['enum_value'], EnumOption);
            }
            if (data.hasOwnProperty('multi_enum_values')) {
                obj['multi_enum_values'] = ApiClient.convertToType(data['multi_enum_values'], [EnumOption]);
            }
            if (data.hasOwnProperty('number_value')) {
                obj['number_value'] = ApiClient.convertToType(data['number_value'], 'Number');
            }
            if (data.hasOwnProperty('text_value')) {
                obj['text_value'] = ApiClient.convertToType(data['text_value'], 'String');
            }
            if (data.hasOwnProperty('display_value')) {
                obj['display_value'] = ApiClient.convertToType(data['display_value'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('precision')) {
                obj['precision'] = ApiClient.convertToType(data['precision'], 'Number');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('currency_code')) {
                obj['currency_code'] = ApiClient.convertToType(data['currency_code'], 'String');
            }
            if (data.hasOwnProperty('custom_label')) {
                obj['custom_label'] = ApiClient.convertToType(data['custom_label'], 'String');
            }
            if (data.hasOwnProperty('custom_label_position')) {
                obj['custom_label_position'] = ApiClient.convertToType(data['custom_label_position'], 'String');
            }
            if (data.hasOwnProperty('has_notifications_enabled')) {
                obj['has_notifications_enabled'] = ApiClient.convertToType(data['has_notifications_enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
CustomFieldBase.prototype['gid'] = undefined;

/**
 * @member {Object} resource_type
 */
CustomFieldBase.prototype['resource_type'] = undefined;

/**
 * The name of the custom field.
 * @member {String} name
 */
CustomFieldBase.prototype['name'] = undefined;

/**
 * The type of the custom field. Must be one of the given values.
 * @member {module:model/CustomFieldBase.ResourceSubtypeEnum} resource_subtype
 */
CustomFieldBase.prototype['resource_subtype'] = undefined;

/**
 * *Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values.
 * @member {module:model/CustomFieldBase.TypeEnum} type
 */
CustomFieldBase.prototype['type'] = undefined;

/**
 * *Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/reference/createenumoptionforcustomfield).
 * @member {Array.<module:model/EnumOption>} enum_options
 */
CustomFieldBase.prototype['enum_options'] = undefined;

/**
 * *Conditional*. Determines if the custom field is enabled or not.
 * @member {Boolean} enabled
 */
CustomFieldBase.prototype['enabled'] = undefined;

/**
 * @member {module:model/CustomFieldCompactAllOfDateValue} date_value
 */
CustomFieldBase.prototype['date_value'] = undefined;

/**
 * @member {module:model/EnumOption} enum_value
 */
CustomFieldBase.prototype['enum_value'] = undefined;

/**
 * *Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a `multi_enum` custom field.
 * @member {Array.<module:model/EnumOption>} multi_enum_values
 */
CustomFieldBase.prototype['multi_enum_values'] = undefined;

/**
 * *Conditional*. This number is the value of a `number` custom field.
 * @member {Number} number_value
 */
CustomFieldBase.prototype['number_value'] = undefined;

/**
 * *Conditional*. This string is the value of a `text` custom field.
 * @member {String} text_value
 */
CustomFieldBase.prototype['text_value'] = undefined;

/**
 * A string representation for the value of the custom field. Integrations that don't require the underlying type should use this field to read values. Using this field will future-proof an app against new custom field types.
 * @member {String} display_value
 */
CustomFieldBase.prototype['display_value'] = undefined;

/**
 * [Opt In](/docs/inputoutput-options). The description of the custom field.
 * @member {String} description
 */
CustomFieldBase.prototype['description'] = undefined;

/**
 * Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive. For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%. The identifier format will always have a precision of 0.
 * @member {Number} precision
 */
CustomFieldBase.prototype['precision'] = undefined;

/**
 * The format of this custom field.
 * @member {module:model/CustomFieldBase.FormatEnum} format
 */
CustomFieldBase.prototype['format'] = undefined;

/**
 * ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`.
 * @member {String} currency_code
 */
CustomFieldBase.prototype['currency_code'] = undefined;

/**
 * This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`.
 * @member {String} custom_label
 */
CustomFieldBase.prototype['custom_label'] = undefined;

/**
 * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
 * @member {module:model/CustomFieldBase.CustomLabelPositionEnum} custom_label_position
 */
CustomFieldBase.prototype['custom_label_position'] = undefined;

/**
 * *Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field.
 * @member {Boolean} has_notifications_enabled
 */
CustomFieldBase.prototype['has_notifications_enabled'] = undefined;


// Implement CustomFieldCompact interface:
/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
CustomFieldCompact.prototype['gid'] = undefined;
/**
 * @member {Object} resource_type
 */
CustomFieldCompact.prototype['resource_type'] = undefined;
/**
 * The name of the custom field.
 * @member {String} name
 */
CustomFieldCompact.prototype['name'] = undefined;
/**
 * The type of the custom field. Must be one of the given values.
 * @member {module:model/CustomFieldCompact.ResourceSubtypeEnum} resource_subtype
 */
CustomFieldCompact.prototype['resource_subtype'] = undefined;
/**
 * *Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values.
 * @member {module:model/CustomFieldCompact.TypeEnum} type
 */
CustomFieldCompact.prototype['type'] = undefined;
/**
 * *Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/reference/createenumoptionforcustomfield).
 * @member {Array.<module:model/EnumOption>} enum_options
 */
CustomFieldCompact.prototype['enum_options'] = undefined;
/**
 * *Conditional*. Determines if the custom field is enabled or not.
 * @member {Boolean} enabled
 */
CustomFieldCompact.prototype['enabled'] = undefined;
/**
 * @member {module:model/CustomFieldCompactAllOfDateValue} date_value
 */
CustomFieldCompact.prototype['date_value'] = undefined;
/**
 * @member {module:model/EnumOption} enum_value
 */
CustomFieldCompact.prototype['enum_value'] = undefined;
/**
 * *Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a `multi_enum` custom field.
 * @member {Array.<module:model/EnumOption>} multi_enum_values
 */
CustomFieldCompact.prototype['multi_enum_values'] = undefined;
/**
 * *Conditional*. This number is the value of a `number` custom field.
 * @member {Number} number_value
 */
CustomFieldCompact.prototype['number_value'] = undefined;
/**
 * *Conditional*. This string is the value of a `text` custom field.
 * @member {String} text_value
 */
CustomFieldCompact.prototype['text_value'] = undefined;
/**
 * A string representation for the value of the custom field. Integrations that don't require the underlying type should use this field to read values. Using this field will future-proof an app against new custom field types.
 * @member {String} display_value
 */
CustomFieldCompact.prototype['display_value'] = undefined;
// Implement CustomFieldBaseAllOf interface:
/**
 * [Opt In](/docs/inputoutput-options). The description of the custom field.
 * @member {String} description
 */
CustomFieldBaseAllOf.prototype['description'] = undefined;
/**
 * Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive. For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%. The identifier format will always have a precision of 0.
 * @member {Number} precision
 */
CustomFieldBaseAllOf.prototype['precision'] = undefined;
/**
 * The format of this custom field.
 * @member {module:model/CustomFieldBaseAllOf.FormatEnum} format
 */
CustomFieldBaseAllOf.prototype['format'] = undefined;
/**
 * ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`.
 * @member {String} currency_code
 */
CustomFieldBaseAllOf.prototype['currency_code'] = undefined;
/**
 * This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`.
 * @member {String} custom_label
 */
CustomFieldBaseAllOf.prototype['custom_label'] = undefined;
/**
 * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
 * @member {module:model/CustomFieldBaseAllOf.CustomLabelPositionEnum} custom_label_position
 */
CustomFieldBaseAllOf.prototype['custom_label_position'] = undefined;
/**
 * *Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field.
 * @member {Boolean} has_notifications_enabled
 */
CustomFieldBaseAllOf.prototype['has_notifications_enabled'] = undefined;



/**
 * Allowed values for the <code>resource_subtype</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldBase['ResourceSubtypeEnum'] = {

    /**
     * value: "text"
     * @const
     */
    "text": "text",

    /**
     * value: "enum"
     * @const
     */
    "enum": "enum",

    /**
     * value: "multi_enum"
     * @const
     */
    "multi_enum": "multi_enum",

    /**
     * value: "number"
     * @const
     */
    "number": "number",

    /**
     * value: "date"
     * @const
     */
    "date": "date",

    /**
     * value: "people"
     * @const
     */
    "people": "people"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldBase['TypeEnum'] = {

    /**
     * value: "text"
     * @const
     */
    "text": "text",

    /**
     * value: "enum"
     * @const
     */
    "enum": "enum",

    /**
     * value: "multi_enum"
     * @const
     */
    "multi_enum": "multi_enum",

    /**
     * value: "number"
     * @const
     */
    "number": "number"
};


/**
 * Allowed values for the <code>format</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldBase['FormatEnum'] = {

    /**
     * value: "currency"
     * @const
     */
    "currency": "currency",

    /**
     * value: "identifier"
     * @const
     */
    "identifier": "identifier",

    /**
     * value: "percentage"
     * @const
     */
    "percentage": "percentage",

    /**
     * value: "custom"
     * @const
     */
    "custom": "custom",

    /**
     * value: "none"
     * @const
     */
    "none": "none"
};


/**
 * Allowed values for the <code>custom_label_position</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldBase['CustomLabelPositionEnum'] = {

    /**
     * value: "prefix"
     * @const
     */
    "prefix": "prefix",

    /**
     * value: "suffix"
     * @const
     */
    "suffix": "suffix"
};



export default CustomFieldBase;

