/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomFieldSettingCompactAllOf model module.
 * @module model/CustomFieldSettingCompactAllOf
 * @version 1.0.1
 */
class CustomFieldSettingCompactAllOf {
    /**
     * Constructs a new <code>CustomFieldSettingCompactAllOf</code>.
     * Custom Fields Settings objects represent the many-to-many join of the Custom Field and Project as well as stores information that is relevant to that particular pairing.
     * @alias module:model/CustomFieldSettingCompactAllOf
     */
    constructor() { 
        
        CustomFieldSettingCompactAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldSettingCompactAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldSettingCompactAllOf} obj Optional instance to populate.
     * @return {module:model/CustomFieldSettingCompactAllOf} The populated <code>CustomFieldSettingCompactAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldSettingCompactAllOf();

            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} resource_type
 */
CustomFieldSettingCompactAllOf.prototype['resource_type'] = undefined;






export default CustomFieldSettingCompactAllOf;

