/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomFieldBaseAllOf model module.
 * @module model/CustomFieldBaseAllOf
 * @version 1.0.1
 */
class CustomFieldBaseAllOf {
    /**
     * Constructs a new <code>CustomFieldBaseAllOf</code>.
     * @alias module:model/CustomFieldBaseAllOf
     */
    constructor() { 
        
        CustomFieldBaseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldBaseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldBaseAllOf} obj Optional instance to populate.
     * @return {module:model/CustomFieldBaseAllOf} The populated <code>CustomFieldBaseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldBaseAllOf();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('precision')) {
                obj['precision'] = ApiClient.convertToType(data['precision'], 'Number');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('currency_code')) {
                obj['currency_code'] = ApiClient.convertToType(data['currency_code'], 'String');
            }
            if (data.hasOwnProperty('custom_label')) {
                obj['custom_label'] = ApiClient.convertToType(data['custom_label'], 'String');
            }
            if (data.hasOwnProperty('custom_label_position')) {
                obj['custom_label_position'] = ApiClient.convertToType(data['custom_label_position'], 'String');
            }
            if (data.hasOwnProperty('has_notifications_enabled')) {
                obj['has_notifications_enabled'] = ApiClient.convertToType(data['has_notifications_enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * [Opt In](/docs/inputoutput-options). The description of the custom field.
 * @member {String} description
 */
CustomFieldBaseAllOf.prototype['description'] = undefined;

/**
 * Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive. For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%. The identifier format will always have a precision of 0.
 * @member {Number} precision
 */
CustomFieldBaseAllOf.prototype['precision'] = undefined;

/**
 * The format of this custom field.
 * @member {module:model/CustomFieldBaseAllOf.FormatEnum} format
 */
CustomFieldBaseAllOf.prototype['format'] = undefined;

/**
 * ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`.
 * @member {String} currency_code
 */
CustomFieldBaseAllOf.prototype['currency_code'] = undefined;

/**
 * This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`.
 * @member {String} custom_label
 */
CustomFieldBaseAllOf.prototype['custom_label'] = undefined;

/**
 * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
 * @member {module:model/CustomFieldBaseAllOf.CustomLabelPositionEnum} custom_label_position
 */
CustomFieldBaseAllOf.prototype['custom_label_position'] = undefined;

/**
 * *Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field.
 * @member {Boolean} has_notifications_enabled
 */
CustomFieldBaseAllOf.prototype['has_notifications_enabled'] = undefined;





/**
 * Allowed values for the <code>format</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldBaseAllOf['FormatEnum'] = {

    /**
     * value: "currency"
     * @const
     */
    "currency": "currency",

    /**
     * value: "identifier"
     * @const
     */
    "identifier": "identifier",

    /**
     * value: "percentage"
     * @const
     */
    "percentage": "percentage",

    /**
     * value: "custom"
     * @const
     */
    "custom": "custom",

    /**
     * value: "none"
     * @const
     */
    "none": "none"
};


/**
 * Allowed values for the <code>custom_label_position</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldBaseAllOf['CustomLabelPositionEnum'] = {

    /**
     * value: "prefix"
     * @const
     */
    "prefix": "prefix",

    /**
     * value: "suffix"
     * @const
     */
    "suffix": "suffix"
};



export default CustomFieldBaseAllOf;

