/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorResponse from './ErrorResponse';
import ErrorResponse5XXAllOf from './ErrorResponse5XXAllOf';
import ErrorResponse5XXAllOfErrors from './ErrorResponse5XXAllOfErrors';

/**
 * The ErrorResponse5XX model module.
 * @module model/ErrorResponse5XX
 * @version 1.0.2
 */
class ErrorResponse5XX {
    /**
     * Constructs a new <code>ErrorResponse5XX</code>.
     * @alias module:model/ErrorResponse5XX
     * @implements module:model/ErrorResponse
     * @implements module:model/ErrorResponse5XXAllOf
     */
    constructor() { 
        ErrorResponse.initialize(this);ErrorResponse5XXAllOf.initialize(this);
        ErrorResponse5XX.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ErrorResponse5XX</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorResponse5XX} obj Optional instance to populate.
     * @return {module:model/ErrorResponse5XX} The populated <code>ErrorResponse5XX</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorResponse5XX();
            ErrorResponse.constructFromObject(data, obj);
            ErrorResponse5XXAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [ErrorResponse5XXAllOfErrors]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ErrorResponse5XXAllOfErrors>} errors
 */
ErrorResponse5XX.prototype['errors'] = undefined;


// Implement ErrorResponse interface:
/**
 * @member {Array.<module:model/ErrorResponseErrorsInner>} errors
 */
ErrorResponse.prototype['errors'] = undefined;
// Implement ErrorResponse5XXAllOf interface:
/**
 * @member {Array.<module:model/ErrorResponse5XXAllOfErrors>} errors
 */
ErrorResponse5XXAllOf.prototype['errors'] = undefined;




export default ErrorResponse5XX;

