/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorResponse from './ErrorResponse';
import GetEvents404ResponseAllOf from './GetEvents404ResponseAllOf';
import GetEvents404ResponseAllOfErrorsInner from './GetEvents404ResponseAllOfErrorsInner';

/**
 * The GetEvents404Response model module.
 * @module model/GetEvents404Response
 * @version 1.0.1
 */
class GetEvents404Response {
    /**
     * Constructs a new <code>GetEvents404Response</code>.
     * @alias module:model/GetEvents404Response
     * @implements module:model/ErrorResponse
     * @implements module:model/GetEvents404ResponseAllOf
     */
    constructor() { 
        ErrorResponse.initialize(this);GetEvents404ResponseAllOf.initialize(this);
        GetEvents404Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetEvents404Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetEvents404Response} obj Optional instance to populate.
     * @return {module:model/GetEvents404Response} The populated <code>GetEvents404Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetEvents404Response();
            ErrorResponse.constructFromObject(data, obj);
            GetEvents404ResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [GetEvents404ResponseAllOfErrorsInner]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GetEvents404ResponseAllOfErrorsInner>} errors
 */
GetEvents404Response.prototype['errors'] = undefined;


// Implement ErrorResponse interface:
/**
 * @member {Array.<module:model/ErrorResponseErrorsInner>} errors
 */
ErrorResponse.prototype['errors'] = undefined;
// Implement GetEvents404ResponseAllOf interface:
/**
 * @member {Array.<module:model/GetEvents404ResponseAllOfErrorsInner>} errors
 */
GetEvents404ResponseAllOf.prototype['errors'] = undefined;




export default GetEvents404Response;

