/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldResponsePeopleValueInner from './CustomFieldResponsePeopleValueInner';

/**
 * The GoalResponseLikesInner model module.
 * @module model/GoalResponseLikesInner
 * @version 1.0.4
 */
class GoalResponseLikesInner {
    /**
     * Constructs a new <code>GoalResponseLikesInner</code>.
     * An object to represent a user&#39;s like.
     * @alias module:model/GoalResponseLikesInner
     */
    constructor() { 
        
        GoalResponseLikesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GoalResponseLikesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoalResponseLikesInner} obj Optional instance to populate.
     * @return {module:model/GoalResponseLikesInner} The populated <code>GoalResponseLikesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoalResponseLikesInner();

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = CustomFieldResponsePeopleValueInner.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * Globally unique identifier of the object, as a string.
 * @member {String} gid
 */
GoalResponseLikesInner.prototype['gid'] = undefined;

/**
 * @member {module:model/CustomFieldResponsePeopleValueInner} user
 */
GoalResponseLikesInner.prototype['user'] = undefined;






export default GoalResponseLikesInner;

