/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AsanaResource from './AsanaResource';
import GoalCompactAllOf from './GoalCompactAllOf';
import UserCompact from './UserCompact';

/**
 * The GoalCompact model module.
 * @module model/GoalCompact
 * @version 1.0.3
 */
class GoalCompact {
    /**
     * Constructs a new <code>GoalCompact</code>.
     * @alias module:model/GoalCompact
     * @implements module:model/AsanaResource
     * @implements module:model/GoalCompactAllOf
     */
    constructor() { 
        AsanaResource.initialize(this);GoalCompactAllOf.initialize(this);
        GoalCompact.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GoalCompact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoalCompact} obj Optional instance to populate.
     * @return {module:model/GoalCompact} The populated <code>GoalCompact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoalCompact();
            AsanaResource.constructFromObject(data, obj);
            GoalCompactAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], UserCompact);
            }
        }
        return obj;
    }


}

/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
GoalCompact.prototype['gid'] = undefined;

/**
 * The base type of this resource.
 * @member {String} resource_type
 */
GoalCompact.prototype['resource_type'] = undefined;

/**
 * The name of the goal.
 * @member {String} name
 */
GoalCompact.prototype['name'] = undefined;

/**
 * @member {module:model/UserCompact} owner
 */
GoalCompact.prototype['owner'] = undefined;


// Implement AsanaResource interface:
/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
AsanaResource.prototype['gid'] = undefined;
/**
 * The base type of this resource.
 * @member {String} resource_type
 */
AsanaResource.prototype['resource_type'] = undefined;
// Implement GoalCompactAllOf interface:
/**
 * The name of the goal.
 * @member {String} name
 */
GoalCompactAllOf.prototype['name'] = undefined;
/**
 * @member {module:model/UserCompact} owner
 */
GoalCompactAllOf.prototype['owner'] = undefined;




export default GoalCompact;

