/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GoalRemoveSupportingRelationshipRequest model module.
 * @module model/GoalRemoveSupportingRelationshipRequest
 * @version 1.0.3
 */
class GoalRemoveSupportingRelationshipRequest {
    /**
     * Constructs a new <code>GoalRemoveSupportingRelationshipRequest</code>.
     * @alias module:model/GoalRemoveSupportingRelationshipRequest
     * @param supportingResource {String} The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, or portfolio.
     */
    constructor(supportingResource) { 
        
        GoalRemoveSupportingRelationshipRequest.initialize(this, supportingResource);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, supportingResource) { 
        obj['supporting_resource'] = supportingResource;
    }

    /**
     * Constructs a <code>GoalRemoveSupportingRelationshipRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoalRemoveSupportingRelationshipRequest} obj Optional instance to populate.
     * @return {module:model/GoalRemoveSupportingRelationshipRequest} The populated <code>GoalRemoveSupportingRelationshipRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoalRemoveSupportingRelationshipRequest();

            if (data.hasOwnProperty('supporting_resource')) {
                obj['supporting_resource'] = ApiClient.convertToType(data['supporting_resource'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, or portfolio.
 * @member {String} supporting_resource
 */
GoalRemoveSupportingRelationshipRequest.prototype['supporting_resource'] = undefined;






export default GoalRemoveSupportingRelationshipRequest;

