/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MembershipResponseAnyOf4UserTaskList model module.
 * @module model/MembershipResponseAnyOf4UserTaskList
 * @version 1.0.4
 */
class MembershipResponseAnyOf4UserTaskList {
    /**
     * Constructs a new <code>MembershipResponseAnyOf4UserTaskList</code>.
     * A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier. A user task list represents the tasks assigned to a particular user. It provides API access to a user’s [My Tasks](https://asana.com/guide/help/fundamentals/my-tasks) view in Asana.
     * @alias module:model/MembershipResponseAnyOf4UserTaskList
     */
    constructor() { 
        
        MembershipResponseAnyOf4UserTaskList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MembershipResponseAnyOf4UserTaskList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MembershipResponseAnyOf4UserTaskList} obj Optional instance to populate.
     * @return {module:model/MembershipResponseAnyOf4UserTaskList} The populated <code>MembershipResponseAnyOf4UserTaskList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MembershipResponseAnyOf4UserTaskList();

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], Object);
            }
            if (data.hasOwnProperty('workspace')) {
                obj['workspace'] = ApiClient.convertToType(data['workspace'], Object);
            }
        }
        return obj;
    }


}

/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
MembershipResponseAnyOf4UserTaskList.prototype['gid'] = undefined;

/**
 * The base type of this resource.
 * @member {String} resource_type
 */
MembershipResponseAnyOf4UserTaskList.prototype['resource_type'] = undefined;

/**
 * The name of the user task list.
 * @member {String} name
 */
MembershipResponseAnyOf4UserTaskList.prototype['name'] = undefined;

/**
 * The owner of the user task list, i.e. the person whose My Tasks is represented by this resource.
 * @member {Object} owner
 */
MembershipResponseAnyOf4UserTaskList.prototype['owner'] = undefined;

/**
 * The workspace in which the user task list is located.
 * @member {Object} workspace
 */
MembershipResponseAnyOf4UserTaskList.prototype['workspace'] = undefined;






export default MembershipResponseAnyOf4UserTaskList;

