/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NextPage model module.
 * @module model/NextPage
 * @version 1.0.2
 */
class NextPage {
    /**
     * Constructs a new <code>NextPage</code>.
     * A object containing information for the next page. If there are no more pages available, null will be returned.
     * @alias module:model/NextPage
     */
    constructor() { 
        
        NextPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NextPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NextPage} obj Optional instance to populate.
     * @return {module:model/NextPage} The populated <code>NextPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NextPage();

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} offset
 */
NextPage.prototype['offset'] = undefined;

/**
 * @member {String} path
 */
NextPage.prototype['path'] = undefined;

/**
 * @member {String} uri
 */
NextPage.prototype['uri'] = undefined;






export default NextPage;

