/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldCompact from './CustomFieldCompact';
import EnumOption from './EnumOption';
import Like from './Like';
import Preview from './Preview';
import ProjectCompact from './ProjectCompact';
import SectionCompact from './SectionCompact';
import StoryBase from './StoryBase';
import StoryCompact from './StoryCompact';
import StoryResponseAllOf from './StoryResponseAllOf';
import StoryResponseDates from './StoryResponseDates';
import TagCompact from './TagCompact';
import TaskCompact from './TaskCompact';
import UserCompact from './UserCompact';

/**
 * The StoryResponse model module.
 * @module model/StoryResponse
 * @version 1.0.3
 */
class StoryResponse {
    /**
     * Constructs a new <code>StoryResponse</code>.
     * @alias module:model/StoryResponse
     * @implements module:model/StoryBase
     * @implements module:model/StoryResponseAllOf
     */
    constructor() { 
        StoryBase.initialize(this);StoryResponseAllOf.initialize(this);
        StoryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoryResponse} obj Optional instance to populate.
     * @return {module:model/StoryResponse} The populated <code>StoryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoryResponse();
            StoryBase.constructFromObject(data, obj);
            StoryResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('resource_subtype')) {
                obj['resource_subtype'] = ApiClient.convertToType(data['resource_subtype'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('html_text')) {
                obj['html_text'] = ApiClient.convertToType(data['html_text'], 'String');
            }
            if (data.hasOwnProperty('is_pinned')) {
                obj['is_pinned'] = ApiClient.convertToType(data['is_pinned'], 'Boolean');
            }
            if (data.hasOwnProperty('sticker_name')) {
                obj['sticker_name'] = ApiClient.convertToType(data['sticker_name'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = UserCompact.constructFromObject(data['created_by']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('is_editable')) {
                obj['is_editable'] = ApiClient.convertToType(data['is_editable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_edited')) {
                obj['is_edited'] = ApiClient.convertToType(data['is_edited'], 'Boolean');
            }
            if (data.hasOwnProperty('hearted')) {
                obj['hearted'] = ApiClient.convertToType(data['hearted'], 'Boolean');
            }
            if (data.hasOwnProperty('hearts')) {
                obj['hearts'] = ApiClient.convertToType(data['hearts'], [Like]);
            }
            if (data.hasOwnProperty('num_hearts')) {
                obj['num_hearts'] = ApiClient.convertToType(data['num_hearts'], 'Number');
            }
            if (data.hasOwnProperty('liked')) {
                obj['liked'] = ApiClient.convertToType(data['liked'], 'Boolean');
            }
            if (data.hasOwnProperty('likes')) {
                obj['likes'] = ApiClient.convertToType(data['likes'], [Like]);
            }
            if (data.hasOwnProperty('num_likes')) {
                obj['num_likes'] = ApiClient.convertToType(data['num_likes'], 'Number');
            }
            if (data.hasOwnProperty('previews')) {
                obj['previews'] = ApiClient.convertToType(data['previews'], [Preview]);
            }
            if (data.hasOwnProperty('old_name')) {
                obj['old_name'] = ApiClient.convertToType(data['old_name'], 'String');
            }
            if (data.hasOwnProperty('new_name')) {
                obj['new_name'] = ApiClient.convertToType(data['new_name'], 'String');
            }
            if (data.hasOwnProperty('old_dates')) {
                obj['old_dates'] = StoryResponseDates.constructFromObject(data['old_dates']);
            }
            if (data.hasOwnProperty('new_dates')) {
                obj['new_dates'] = StoryResponseDates.constructFromObject(data['new_dates']);
            }
            if (data.hasOwnProperty('old_resource_subtype')) {
                obj['old_resource_subtype'] = ApiClient.convertToType(data['old_resource_subtype'], 'String');
            }
            if (data.hasOwnProperty('new_resource_subtype')) {
                obj['new_resource_subtype'] = ApiClient.convertToType(data['new_resource_subtype'], 'String');
            }
            if (data.hasOwnProperty('story')) {
                obj['story'] = StoryCompact.constructFromObject(data['story']);
            }
            if (data.hasOwnProperty('assignee')) {
                obj['assignee'] = UserCompact.constructFromObject(data['assignee']);
            }
            if (data.hasOwnProperty('follower')) {
                obj['follower'] = UserCompact.constructFromObject(data['follower']);
            }
            if (data.hasOwnProperty('old_section')) {
                obj['old_section'] = SectionCompact.constructFromObject(data['old_section']);
            }
            if (data.hasOwnProperty('new_section')) {
                obj['new_section'] = SectionCompact.constructFromObject(data['new_section']);
            }
            if (data.hasOwnProperty('task')) {
                obj['task'] = TaskCompact.constructFromObject(data['task']);
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ProjectCompact.constructFromObject(data['project']);
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = TagCompact.constructFromObject(data['tag']);
            }
            if (data.hasOwnProperty('custom_field')) {
                obj['custom_field'] = CustomFieldCompact.constructFromObject(data['custom_field']);
            }
            if (data.hasOwnProperty('old_text_value')) {
                obj['old_text_value'] = ApiClient.convertToType(data['old_text_value'], 'String');
            }
            if (data.hasOwnProperty('new_text_value')) {
                obj['new_text_value'] = ApiClient.convertToType(data['new_text_value'], 'String');
            }
            if (data.hasOwnProperty('old_number_value')) {
                obj['old_number_value'] = ApiClient.convertToType(data['old_number_value'], 'Number');
            }
            if (data.hasOwnProperty('new_number_value')) {
                obj['new_number_value'] = ApiClient.convertToType(data['new_number_value'], 'Number');
            }
            if (data.hasOwnProperty('old_enum_value')) {
                obj['old_enum_value'] = EnumOption.constructFromObject(data['old_enum_value']);
            }
            if (data.hasOwnProperty('new_enum_value')) {
                obj['new_enum_value'] = EnumOption.constructFromObject(data['new_enum_value']);
            }
            if (data.hasOwnProperty('old_date_value')) {
                obj['old_date_value'] = ApiClient.convertToType(data['old_date_value'], StoryResponseDates);
            }
            if (data.hasOwnProperty('new_date_value')) {
                obj['new_date_value'] = ApiClient.convertToType(data['new_date_value'], StoryResponseDates);
            }
            if (data.hasOwnProperty('old_people_value')) {
                obj['old_people_value'] = ApiClient.convertToType(data['old_people_value'], [UserCompact]);
            }
            if (data.hasOwnProperty('new_people_value')) {
                obj['new_people_value'] = ApiClient.convertToType(data['new_people_value'], [UserCompact]);
            }
            if (data.hasOwnProperty('old_multi_enum_values')) {
                obj['old_multi_enum_values'] = ApiClient.convertToType(data['old_multi_enum_values'], [EnumOption]);
            }
            if (data.hasOwnProperty('new_multi_enum_values')) {
                obj['new_multi_enum_values'] = ApiClient.convertToType(data['new_multi_enum_values'], [EnumOption]);
            }
            if (data.hasOwnProperty('new_approval_status')) {
                obj['new_approval_status'] = ApiClient.convertToType(data['new_approval_status'], 'String');
            }
            if (data.hasOwnProperty('old_approval_status')) {
                obj['old_approval_status'] = ApiClient.convertToType(data['old_approval_status'], 'String');
            }
            if (data.hasOwnProperty('duplicate_of')) {
                obj['duplicate_of'] = TaskCompact.constructFromObject(data['duplicate_of']);
            }
            if (data.hasOwnProperty('duplicated_from')) {
                obj['duplicated_from'] = TaskCompact.constructFromObject(data['duplicated_from']);
            }
            if (data.hasOwnProperty('dependency')) {
                obj['dependency'] = TaskCompact.constructFromObject(data['dependency']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], TaskCompact);
            }
        }
        return obj;
    }


}

/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
StoryResponse.prototype['gid'] = undefined;

/**
 * The base type of this resource.
 * @member {String} resource_type
 */
StoryResponse.prototype['resource_type'] = undefined;

/**
 * The time at which this resource was created.
 * @member {Date} created_at
 */
StoryResponse.prototype['created_at'] = undefined;

/**
 * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
 * @member {String} resource_subtype
 */
StoryResponse.prototype['resource_subtype'] = undefined;

/**
 * The plain text of the comment to add. Cannot be used with html_text.
 * @member {String} text
 */
StoryResponse.prototype['text'] = undefined;

/**
 * [Opt In](/docs/inputoutput-options). HTML formatted text for a comment. This will not include the name of the creator.
 * @member {String} html_text
 */
StoryResponse.prototype['html_text'] = undefined;

/**
 * *Conditional*. Whether the story should be pinned on the resource.
 * @member {Boolean} is_pinned
 */
StoryResponse.prototype['is_pinned'] = undefined;

/**
 * The name of the sticker in this story. `null` if there is no sticker.
 * @member {module:model/StoryResponse.StickerNameEnum} sticker_name
 */
StoryResponse.prototype['sticker_name'] = undefined;

/**
 * @member {module:model/UserCompact} created_by
 */
StoryResponse.prototype['created_by'] = undefined;

/**
 * @member {module:model/StoryResponse.TypeEnum} type
 */
StoryResponse.prototype['type'] = undefined;

/**
 * *Conditional*. Whether the text of the story can be edited after creation.
 * @member {Boolean} is_editable
 */
StoryResponse.prototype['is_editable'] = undefined;

/**
 * *Conditional*. Whether the text of the story has been edited after creation.
 * @member {Boolean} is_edited
 */
StoryResponse.prototype['is_edited'] = undefined;

/**
 * *Deprecated - please use likes instead* *Conditional*. True if the story is hearted by the authorized user, false if not.
 * @member {Boolean} hearted
 */
StoryResponse.prototype['hearted'] = undefined;

/**
 * *Deprecated - please use likes instead*  *Conditional*. Array of likes for users who have hearted this story.
 * @member {Array.<module:model/Like>} hearts
 */
StoryResponse.prototype['hearts'] = undefined;

/**
 * *Deprecated - please use likes instead*  *Conditional*. The number of users who have hearted this story.
 * @member {Number} num_hearts
 */
StoryResponse.prototype['num_hearts'] = undefined;

/**
 * *Conditional*. True if the story is liked by the authorized user, false if not.
 * @member {Boolean} liked
 */
StoryResponse.prototype['liked'] = undefined;

/**
 * *Conditional*. Array of likes for users who have liked this story.
 * @member {Array.<module:model/Like>} likes
 */
StoryResponse.prototype['likes'] = undefined;

/**
 * *Conditional*. The number of users who have liked this story.
 * @member {Number} num_likes
 */
StoryResponse.prototype['num_likes'] = undefined;

/**
 * *Conditional*. A collection of previews to be displayed in the story.  *Note: This property only exists for comment stories.*
 * @member {Array.<module:model/Preview>} previews
 */
StoryResponse.prototype['previews'] = undefined;

/**
 * *Conditional*'
 * @member {String} old_name
 */
StoryResponse.prototype['old_name'] = undefined;

/**
 * *Conditional*
 * @member {String} new_name
 */
StoryResponse.prototype['new_name'] = undefined;

/**
 * @member {module:model/StoryResponseDates} old_dates
 */
StoryResponse.prototype['old_dates'] = undefined;

/**
 * @member {module:model/StoryResponseDates} new_dates
 */
StoryResponse.prototype['new_dates'] = undefined;

/**
 * *Conditional*
 * @member {String} old_resource_subtype
 */
StoryResponse.prototype['old_resource_subtype'] = undefined;

/**
 * *Conditional*
 * @member {String} new_resource_subtype
 */
StoryResponse.prototype['new_resource_subtype'] = undefined;

/**
 * @member {module:model/StoryCompact} story
 */
StoryResponse.prototype['story'] = undefined;

/**
 * @member {module:model/UserCompact} assignee
 */
StoryResponse.prototype['assignee'] = undefined;

/**
 * @member {module:model/UserCompact} follower
 */
StoryResponse.prototype['follower'] = undefined;

/**
 * @member {module:model/SectionCompact} old_section
 */
StoryResponse.prototype['old_section'] = undefined;

/**
 * @member {module:model/SectionCompact} new_section
 */
StoryResponse.prototype['new_section'] = undefined;

/**
 * @member {module:model/TaskCompact} task
 */
StoryResponse.prototype['task'] = undefined;

/**
 * @member {module:model/ProjectCompact} project
 */
StoryResponse.prototype['project'] = undefined;

/**
 * @member {module:model/TagCompact} tag
 */
StoryResponse.prototype['tag'] = undefined;

/**
 * @member {module:model/CustomFieldCompact} custom_field
 */
StoryResponse.prototype['custom_field'] = undefined;

/**
 * *Conditional*
 * @member {String} old_text_value
 */
StoryResponse.prototype['old_text_value'] = undefined;

/**
 * *Conditional*
 * @member {String} new_text_value
 */
StoryResponse.prototype['new_text_value'] = undefined;

/**
 * *Conditional*
 * @member {Number} old_number_value
 */
StoryResponse.prototype['old_number_value'] = undefined;

/**
 * *Conditional*
 * @member {Number} new_number_value
 */
StoryResponse.prototype['new_number_value'] = undefined;

/**
 * @member {module:model/EnumOption} old_enum_value
 */
StoryResponse.prototype['old_enum_value'] = undefined;

/**
 * @member {module:model/EnumOption} new_enum_value
 */
StoryResponse.prototype['new_enum_value'] = undefined;

/**
 * @member {module:model/StoryResponseDates} old_date_value
 */
StoryResponse.prototype['old_date_value'] = undefined;

/**
 * @member {module:model/StoryResponseDates} new_date_value
 */
StoryResponse.prototype['new_date_value'] = undefined;

/**
 * *Conditional*. The old value of a people custom field story.
 * @member {Array.<module:model/UserCompact>} old_people_value
 */
StoryResponse.prototype['old_people_value'] = undefined;

/**
 * *Conditional*. The new value of a people custom field story.
 * @member {Array.<module:model/UserCompact>} new_people_value
 */
StoryResponse.prototype['new_people_value'] = undefined;

/**
 * *Conditional*. The old value of a multi-enum custom field story.
 * @member {Array.<module:model/EnumOption>} old_multi_enum_values
 */
StoryResponse.prototype['old_multi_enum_values'] = undefined;

/**
 * *Conditional*. The new value of a multi-enum custom field story.
 * @member {Array.<module:model/EnumOption>} new_multi_enum_values
 */
StoryResponse.prototype['new_multi_enum_values'] = undefined;

/**
 * *Conditional*. The new value of approval status.
 * @member {String} new_approval_status
 */
StoryResponse.prototype['new_approval_status'] = undefined;

/**
 * *Conditional*. The old value of approval status.
 * @member {String} old_approval_status
 */
StoryResponse.prototype['old_approval_status'] = undefined;

/**
 * @member {module:model/TaskCompact} duplicate_of
 */
StoryResponse.prototype['duplicate_of'] = undefined;

/**
 * @member {module:model/TaskCompact} duplicated_from
 */
StoryResponse.prototype['duplicated_from'] = undefined;

/**
 * @member {module:model/TaskCompact} dependency
 */
StoryResponse.prototype['dependency'] = undefined;

/**
 * The component of the Asana product the user used to trigger the story.
 * @member {module:model/StoryResponse.SourceEnum} source
 */
StoryResponse.prototype['source'] = undefined;

/**
 * @member {module:model/TaskCompact} target
 */
StoryResponse.prototype['target'] = undefined;


// Implement StoryBase interface:
/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
StoryBase.prototype['gid'] = undefined;
/**
 * The base type of this resource.
 * @member {String} resource_type
 */
StoryBase.prototype['resource_type'] = undefined;
/**
 * The time at which this resource was created.
 * @member {Date} created_at
 */
StoryBase.prototype['created_at'] = undefined;
/**
 * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
 * @member {String} resource_subtype
 */
StoryBase.prototype['resource_subtype'] = undefined;
/**
 * The plain text of the comment to add. Cannot be used with html_text.
 * @member {String} text
 */
StoryBase.prototype['text'] = undefined;
/**
 * [Opt In](/docs/inputoutput-options). HTML formatted text for a comment. This will not include the name of the creator.
 * @member {String} html_text
 */
StoryBase.prototype['html_text'] = undefined;
/**
 * *Conditional*. Whether the story should be pinned on the resource.
 * @member {Boolean} is_pinned
 */
StoryBase.prototype['is_pinned'] = undefined;
/**
 * The name of the sticker in this story. `null` if there is no sticker.
 * @member {module:model/StoryBase.StickerNameEnum} sticker_name
 */
StoryBase.prototype['sticker_name'] = undefined;
// Implement StoryResponseAllOf interface:
/**
 * @member {module:model/UserCompact} created_by
 */
StoryResponseAllOf.prototype['created_by'] = undefined;
/**
 * @member {module:model/StoryResponseAllOf.TypeEnum} type
 */
StoryResponseAllOf.prototype['type'] = undefined;
/**
 * *Conditional*. Whether the text of the story can be edited after creation.
 * @member {Boolean} is_editable
 */
StoryResponseAllOf.prototype['is_editable'] = undefined;
/**
 * *Conditional*. Whether the text of the story has been edited after creation.
 * @member {Boolean} is_edited
 */
StoryResponseAllOf.prototype['is_edited'] = undefined;
/**
 * *Deprecated - please use likes instead* *Conditional*. True if the story is hearted by the authorized user, false if not.
 * @member {Boolean} hearted
 */
StoryResponseAllOf.prototype['hearted'] = undefined;
/**
 * *Deprecated - please use likes instead*  *Conditional*. Array of likes for users who have hearted this story.
 * @member {Array.<module:model/Like>} hearts
 */
StoryResponseAllOf.prototype['hearts'] = undefined;
/**
 * *Deprecated - please use likes instead*  *Conditional*. The number of users who have hearted this story.
 * @member {Number} num_hearts
 */
StoryResponseAllOf.prototype['num_hearts'] = undefined;
/**
 * *Conditional*. True if the story is liked by the authorized user, false if not.
 * @member {Boolean} liked
 */
StoryResponseAllOf.prototype['liked'] = undefined;
/**
 * *Conditional*. Array of likes for users who have liked this story.
 * @member {Array.<module:model/Like>} likes
 */
StoryResponseAllOf.prototype['likes'] = undefined;
/**
 * *Conditional*. The number of users who have liked this story.
 * @member {Number} num_likes
 */
StoryResponseAllOf.prototype['num_likes'] = undefined;
/**
 * *Conditional*. A collection of previews to be displayed in the story.  *Note: This property only exists for comment stories.*
 * @member {Array.<module:model/Preview>} previews
 */
StoryResponseAllOf.prototype['previews'] = undefined;
/**
 * *Conditional*'
 * @member {String} old_name
 */
StoryResponseAllOf.prototype['old_name'] = undefined;
/**
 * *Conditional*
 * @member {String} new_name
 */
StoryResponseAllOf.prototype['new_name'] = undefined;
/**
 * @member {module:model/StoryResponseDates} old_dates
 */
StoryResponseAllOf.prototype['old_dates'] = undefined;
/**
 * @member {module:model/StoryResponseDates} new_dates
 */
StoryResponseAllOf.prototype['new_dates'] = undefined;
/**
 * *Conditional*
 * @member {String} old_resource_subtype
 */
StoryResponseAllOf.prototype['old_resource_subtype'] = undefined;
/**
 * *Conditional*
 * @member {String} new_resource_subtype
 */
StoryResponseAllOf.prototype['new_resource_subtype'] = undefined;
/**
 * @member {module:model/StoryCompact} story
 */
StoryResponseAllOf.prototype['story'] = undefined;
/**
 * @member {module:model/UserCompact} assignee
 */
StoryResponseAllOf.prototype['assignee'] = undefined;
/**
 * @member {module:model/UserCompact} follower
 */
StoryResponseAllOf.prototype['follower'] = undefined;
/**
 * @member {module:model/SectionCompact} old_section
 */
StoryResponseAllOf.prototype['old_section'] = undefined;
/**
 * @member {module:model/SectionCompact} new_section
 */
StoryResponseAllOf.prototype['new_section'] = undefined;
/**
 * @member {module:model/TaskCompact} task
 */
StoryResponseAllOf.prototype['task'] = undefined;
/**
 * @member {module:model/ProjectCompact} project
 */
StoryResponseAllOf.prototype['project'] = undefined;
/**
 * @member {module:model/TagCompact} tag
 */
StoryResponseAllOf.prototype['tag'] = undefined;
/**
 * @member {module:model/CustomFieldCompact} custom_field
 */
StoryResponseAllOf.prototype['custom_field'] = undefined;
/**
 * *Conditional*
 * @member {String} old_text_value
 */
StoryResponseAllOf.prototype['old_text_value'] = undefined;
/**
 * *Conditional*
 * @member {String} new_text_value
 */
StoryResponseAllOf.prototype['new_text_value'] = undefined;
/**
 * *Conditional*
 * @member {Number} old_number_value
 */
StoryResponseAllOf.prototype['old_number_value'] = undefined;
/**
 * *Conditional*
 * @member {Number} new_number_value
 */
StoryResponseAllOf.prototype['new_number_value'] = undefined;
/**
 * @member {module:model/EnumOption} old_enum_value
 */
StoryResponseAllOf.prototype['old_enum_value'] = undefined;
/**
 * @member {module:model/EnumOption} new_enum_value
 */
StoryResponseAllOf.prototype['new_enum_value'] = undefined;
/**
 * @member {module:model/StoryResponseDates} old_date_value
 */
StoryResponseAllOf.prototype['old_date_value'] = undefined;
/**
 * @member {module:model/StoryResponseDates} new_date_value
 */
StoryResponseAllOf.prototype['new_date_value'] = undefined;
/**
 * *Conditional*. The old value of a people custom field story.
 * @member {Array.<module:model/UserCompact>} old_people_value
 */
StoryResponseAllOf.prototype['old_people_value'] = undefined;
/**
 * *Conditional*. The new value of a people custom field story.
 * @member {Array.<module:model/UserCompact>} new_people_value
 */
StoryResponseAllOf.prototype['new_people_value'] = undefined;
/**
 * *Conditional*. The old value of a multi-enum custom field story.
 * @member {Array.<module:model/EnumOption>} old_multi_enum_values
 */
StoryResponseAllOf.prototype['old_multi_enum_values'] = undefined;
/**
 * *Conditional*. The new value of a multi-enum custom field story.
 * @member {Array.<module:model/EnumOption>} new_multi_enum_values
 */
StoryResponseAllOf.prototype['new_multi_enum_values'] = undefined;
/**
 * *Conditional*. The new value of approval status.
 * @member {String} new_approval_status
 */
StoryResponseAllOf.prototype['new_approval_status'] = undefined;
/**
 * *Conditional*. The old value of approval status.
 * @member {String} old_approval_status
 */
StoryResponseAllOf.prototype['old_approval_status'] = undefined;
/**
 * @member {module:model/TaskCompact} duplicate_of
 */
StoryResponseAllOf.prototype['duplicate_of'] = undefined;
/**
 * @member {module:model/TaskCompact} duplicated_from
 */
StoryResponseAllOf.prototype['duplicated_from'] = undefined;
/**
 * @member {module:model/TaskCompact} dependency
 */
StoryResponseAllOf.prototype['dependency'] = undefined;
/**
 * The component of the Asana product the user used to trigger the story.
 * @member {module:model/StoryResponseAllOf.SourceEnum} source
 */
StoryResponseAllOf.prototype['source'] = undefined;
/**
 * @member {module:model/TaskCompact} target
 */
StoryResponseAllOf.prototype['target'] = undefined;



/**
 * Allowed values for the <code>sticker_name</code> property.
 * @enum {String}
 * @readonly
 */
StoryResponse['StickerNameEnum'] = {

    /**
     * value: "green_checkmark"
     * @const
     */
    "green_checkmark": "green_checkmark",

    /**
     * value: "people_dancing"
     * @const
     */
    "people_dancing": "people_dancing",

    /**
     * value: "dancing_unicorn"
     * @const
     */
    "dancing_unicorn": "dancing_unicorn",

    /**
     * value: "heart"
     * @const
     */
    "heart": "heart",

    /**
     * value: "party_popper"
     * @const
     */
    "party_popper": "party_popper",

    /**
     * value: "people_waving_flags"
     * @const
     */
    "people_waving_flags": "people_waving_flags",

    /**
     * value: "splashing_narwhal"
     * @const
     */
    "splashing_narwhal": "splashing_narwhal",

    /**
     * value: "trophy"
     * @const
     */
    "trophy": "trophy",

    /**
     * value: "yeti_riding_unicorn"
     * @const
     */
    "yeti_riding_unicorn": "yeti_riding_unicorn",

    /**
     * value: "celebrating_people"
     * @const
     */
    "celebrating_people": "celebrating_people",

    /**
     * value: "determined_climbers"
     * @const
     */
    "determined_climbers": "determined_climbers",

    /**
     * value: "phoenix_spreading_love"
     * @const
     */
    "phoenix_spreading_love": "phoenix_spreading_love"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
StoryResponse['TypeEnum'] = {

    /**
     * value: "comment"
     * @const
     */
    "comment": "comment",

    /**
     * value: "system"
     * @const
     */
    "system": "system"
};


/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
StoryResponse['SourceEnum'] = {

    /**
     * value: "web"
     * @const
     */
    "web": "web",

    /**
     * value: "email"
     * @const
     */
    "email": "email",

    /**
     * value: "mobile"
     * @const
     */
    "mobile": "mobile",

    /**
     * value: "api"
     * @const
     */
    "api": "api",

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown"
};



export default StoryResponse;

