/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldCompact from './CustomFieldCompact';
import EnumOption from './EnumOption';
import Like from './Like';
import Preview from './Preview';
import ProjectCompact from './ProjectCompact';
import SectionCompact from './SectionCompact';
import StoryCompact from './StoryCompact';
import StoryResponseDates from './StoryResponseDates';
import TagCompact from './TagCompact';
import TaskCompact from './TaskCompact';
import UserCompact from './UserCompact';

/**
 * The StoryResponseAllOf model module.
 * @module model/StoryResponseAllOf
 * @version 1.0.3
 */
class StoryResponseAllOf {
    /**
     * Constructs a new <code>StoryResponseAllOf</code>.
     * @alias module:model/StoryResponseAllOf
     */
    constructor() { 
        
        StoryResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoryResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoryResponseAllOf} obj Optional instance to populate.
     * @return {module:model/StoryResponseAllOf} The populated <code>StoryResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoryResponseAllOf();

            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = UserCompact.constructFromObject(data['created_by']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('is_editable')) {
                obj['is_editable'] = ApiClient.convertToType(data['is_editable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_edited')) {
                obj['is_edited'] = ApiClient.convertToType(data['is_edited'], 'Boolean');
            }
            if (data.hasOwnProperty('hearted')) {
                obj['hearted'] = ApiClient.convertToType(data['hearted'], 'Boolean');
            }
            if (data.hasOwnProperty('hearts')) {
                obj['hearts'] = ApiClient.convertToType(data['hearts'], [Like]);
            }
            if (data.hasOwnProperty('num_hearts')) {
                obj['num_hearts'] = ApiClient.convertToType(data['num_hearts'], 'Number');
            }
            if (data.hasOwnProperty('liked')) {
                obj['liked'] = ApiClient.convertToType(data['liked'], 'Boolean');
            }
            if (data.hasOwnProperty('likes')) {
                obj['likes'] = ApiClient.convertToType(data['likes'], [Like]);
            }
            if (data.hasOwnProperty('num_likes')) {
                obj['num_likes'] = ApiClient.convertToType(data['num_likes'], 'Number');
            }
            if (data.hasOwnProperty('previews')) {
                obj['previews'] = ApiClient.convertToType(data['previews'], [Preview]);
            }
            if (data.hasOwnProperty('old_name')) {
                obj['old_name'] = ApiClient.convertToType(data['old_name'], 'String');
            }
            if (data.hasOwnProperty('new_name')) {
                obj['new_name'] = ApiClient.convertToType(data['new_name'], 'String');
            }
            if (data.hasOwnProperty('old_dates')) {
                obj['old_dates'] = StoryResponseDates.constructFromObject(data['old_dates']);
            }
            if (data.hasOwnProperty('new_dates')) {
                obj['new_dates'] = StoryResponseDates.constructFromObject(data['new_dates']);
            }
            if (data.hasOwnProperty('old_resource_subtype')) {
                obj['old_resource_subtype'] = ApiClient.convertToType(data['old_resource_subtype'], 'String');
            }
            if (data.hasOwnProperty('new_resource_subtype')) {
                obj['new_resource_subtype'] = ApiClient.convertToType(data['new_resource_subtype'], 'String');
            }
            if (data.hasOwnProperty('story')) {
                obj['story'] = StoryCompact.constructFromObject(data['story']);
            }
            if (data.hasOwnProperty('assignee')) {
                obj['assignee'] = UserCompact.constructFromObject(data['assignee']);
            }
            if (data.hasOwnProperty('follower')) {
                obj['follower'] = UserCompact.constructFromObject(data['follower']);
            }
            if (data.hasOwnProperty('old_section')) {
                obj['old_section'] = SectionCompact.constructFromObject(data['old_section']);
            }
            if (data.hasOwnProperty('new_section')) {
                obj['new_section'] = SectionCompact.constructFromObject(data['new_section']);
            }
            if (data.hasOwnProperty('task')) {
                obj['task'] = TaskCompact.constructFromObject(data['task']);
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ProjectCompact.constructFromObject(data['project']);
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = TagCompact.constructFromObject(data['tag']);
            }
            if (data.hasOwnProperty('custom_field')) {
                obj['custom_field'] = CustomFieldCompact.constructFromObject(data['custom_field']);
            }
            if (data.hasOwnProperty('old_text_value')) {
                obj['old_text_value'] = ApiClient.convertToType(data['old_text_value'], 'String');
            }
            if (data.hasOwnProperty('new_text_value')) {
                obj['new_text_value'] = ApiClient.convertToType(data['new_text_value'], 'String');
            }
            if (data.hasOwnProperty('old_number_value')) {
                obj['old_number_value'] = ApiClient.convertToType(data['old_number_value'], 'Number');
            }
            if (data.hasOwnProperty('new_number_value')) {
                obj['new_number_value'] = ApiClient.convertToType(data['new_number_value'], 'Number');
            }
            if (data.hasOwnProperty('old_enum_value')) {
                obj['old_enum_value'] = EnumOption.constructFromObject(data['old_enum_value']);
            }
            if (data.hasOwnProperty('new_enum_value')) {
                obj['new_enum_value'] = EnumOption.constructFromObject(data['new_enum_value']);
            }
            if (data.hasOwnProperty('old_date_value')) {
                obj['old_date_value'] = ApiClient.convertToType(data['old_date_value'], StoryResponseDates);
            }
            if (data.hasOwnProperty('new_date_value')) {
                obj['new_date_value'] = ApiClient.convertToType(data['new_date_value'], StoryResponseDates);
            }
            if (data.hasOwnProperty('old_people_value')) {
                obj['old_people_value'] = ApiClient.convertToType(data['old_people_value'], [UserCompact]);
            }
            if (data.hasOwnProperty('new_people_value')) {
                obj['new_people_value'] = ApiClient.convertToType(data['new_people_value'], [UserCompact]);
            }
            if (data.hasOwnProperty('old_multi_enum_values')) {
                obj['old_multi_enum_values'] = ApiClient.convertToType(data['old_multi_enum_values'], [EnumOption]);
            }
            if (data.hasOwnProperty('new_multi_enum_values')) {
                obj['new_multi_enum_values'] = ApiClient.convertToType(data['new_multi_enum_values'], [EnumOption]);
            }
            if (data.hasOwnProperty('new_approval_status')) {
                obj['new_approval_status'] = ApiClient.convertToType(data['new_approval_status'], 'String');
            }
            if (data.hasOwnProperty('old_approval_status')) {
                obj['old_approval_status'] = ApiClient.convertToType(data['old_approval_status'], 'String');
            }
            if (data.hasOwnProperty('duplicate_of')) {
                obj['duplicate_of'] = TaskCompact.constructFromObject(data['duplicate_of']);
            }
            if (data.hasOwnProperty('duplicated_from')) {
                obj['duplicated_from'] = TaskCompact.constructFromObject(data['duplicated_from']);
            }
            if (data.hasOwnProperty('dependency')) {
                obj['dependency'] = TaskCompact.constructFromObject(data['dependency']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], TaskCompact);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserCompact} created_by
 */
StoryResponseAllOf.prototype['created_by'] = undefined;

/**
 * @member {module:model/StoryResponseAllOf.TypeEnum} type
 */
StoryResponseAllOf.prototype['type'] = undefined;

/**
 * *Conditional*. Whether the text of the story can be edited after creation.
 * @member {Boolean} is_editable
 */
StoryResponseAllOf.prototype['is_editable'] = undefined;

/**
 * *Conditional*. Whether the text of the story has been edited after creation.
 * @member {Boolean} is_edited
 */
StoryResponseAllOf.prototype['is_edited'] = undefined;

/**
 * *Deprecated - please use likes instead* *Conditional*. True if the story is hearted by the authorized user, false if not.
 * @member {Boolean} hearted
 */
StoryResponseAllOf.prototype['hearted'] = undefined;

/**
 * *Deprecated - please use likes instead*  *Conditional*. Array of likes for users who have hearted this story.
 * @member {Array.<module:model/Like>} hearts
 */
StoryResponseAllOf.prototype['hearts'] = undefined;

/**
 * *Deprecated - please use likes instead*  *Conditional*. The number of users who have hearted this story.
 * @member {Number} num_hearts
 */
StoryResponseAllOf.prototype['num_hearts'] = undefined;

/**
 * *Conditional*. True if the story is liked by the authorized user, false if not.
 * @member {Boolean} liked
 */
StoryResponseAllOf.prototype['liked'] = undefined;

/**
 * *Conditional*. Array of likes for users who have liked this story.
 * @member {Array.<module:model/Like>} likes
 */
StoryResponseAllOf.prototype['likes'] = undefined;

/**
 * *Conditional*. The number of users who have liked this story.
 * @member {Number} num_likes
 */
StoryResponseAllOf.prototype['num_likes'] = undefined;

/**
 * *Conditional*. A collection of previews to be displayed in the story.  *Note: This property only exists for comment stories.*
 * @member {Array.<module:model/Preview>} previews
 */
StoryResponseAllOf.prototype['previews'] = undefined;

/**
 * *Conditional*'
 * @member {String} old_name
 */
StoryResponseAllOf.prototype['old_name'] = undefined;

/**
 * *Conditional*
 * @member {String} new_name
 */
StoryResponseAllOf.prototype['new_name'] = undefined;

/**
 * @member {module:model/StoryResponseDates} old_dates
 */
StoryResponseAllOf.prototype['old_dates'] = undefined;

/**
 * @member {module:model/StoryResponseDates} new_dates
 */
StoryResponseAllOf.prototype['new_dates'] = undefined;

/**
 * *Conditional*
 * @member {String} old_resource_subtype
 */
StoryResponseAllOf.prototype['old_resource_subtype'] = undefined;

/**
 * *Conditional*
 * @member {String} new_resource_subtype
 */
StoryResponseAllOf.prototype['new_resource_subtype'] = undefined;

/**
 * @member {module:model/StoryCompact} story
 */
StoryResponseAllOf.prototype['story'] = undefined;

/**
 * @member {module:model/UserCompact} assignee
 */
StoryResponseAllOf.prototype['assignee'] = undefined;

/**
 * @member {module:model/UserCompact} follower
 */
StoryResponseAllOf.prototype['follower'] = undefined;

/**
 * @member {module:model/SectionCompact} old_section
 */
StoryResponseAllOf.prototype['old_section'] = undefined;

/**
 * @member {module:model/SectionCompact} new_section
 */
StoryResponseAllOf.prototype['new_section'] = undefined;

/**
 * @member {module:model/TaskCompact} task
 */
StoryResponseAllOf.prototype['task'] = undefined;

/**
 * @member {module:model/ProjectCompact} project
 */
StoryResponseAllOf.prototype['project'] = undefined;

/**
 * @member {module:model/TagCompact} tag
 */
StoryResponseAllOf.prototype['tag'] = undefined;

/**
 * @member {module:model/CustomFieldCompact} custom_field
 */
StoryResponseAllOf.prototype['custom_field'] = undefined;

/**
 * *Conditional*
 * @member {String} old_text_value
 */
StoryResponseAllOf.prototype['old_text_value'] = undefined;

/**
 * *Conditional*
 * @member {String} new_text_value
 */
StoryResponseAllOf.prototype['new_text_value'] = undefined;

/**
 * *Conditional*
 * @member {Number} old_number_value
 */
StoryResponseAllOf.prototype['old_number_value'] = undefined;

/**
 * *Conditional*
 * @member {Number} new_number_value
 */
StoryResponseAllOf.prototype['new_number_value'] = undefined;

/**
 * @member {module:model/EnumOption} old_enum_value
 */
StoryResponseAllOf.prototype['old_enum_value'] = undefined;

/**
 * @member {module:model/EnumOption} new_enum_value
 */
StoryResponseAllOf.prototype['new_enum_value'] = undefined;

/**
 * @member {module:model/StoryResponseDates} old_date_value
 */
StoryResponseAllOf.prototype['old_date_value'] = undefined;

/**
 * @member {module:model/StoryResponseDates} new_date_value
 */
StoryResponseAllOf.prototype['new_date_value'] = undefined;

/**
 * *Conditional*. The old value of a people custom field story.
 * @member {Array.<module:model/UserCompact>} old_people_value
 */
StoryResponseAllOf.prototype['old_people_value'] = undefined;

/**
 * *Conditional*. The new value of a people custom field story.
 * @member {Array.<module:model/UserCompact>} new_people_value
 */
StoryResponseAllOf.prototype['new_people_value'] = undefined;

/**
 * *Conditional*. The old value of a multi-enum custom field story.
 * @member {Array.<module:model/EnumOption>} old_multi_enum_values
 */
StoryResponseAllOf.prototype['old_multi_enum_values'] = undefined;

/**
 * *Conditional*. The new value of a multi-enum custom field story.
 * @member {Array.<module:model/EnumOption>} new_multi_enum_values
 */
StoryResponseAllOf.prototype['new_multi_enum_values'] = undefined;

/**
 * *Conditional*. The new value of approval status.
 * @member {String} new_approval_status
 */
StoryResponseAllOf.prototype['new_approval_status'] = undefined;

/**
 * *Conditional*. The old value of approval status.
 * @member {String} old_approval_status
 */
StoryResponseAllOf.prototype['old_approval_status'] = undefined;

/**
 * @member {module:model/TaskCompact} duplicate_of
 */
StoryResponseAllOf.prototype['duplicate_of'] = undefined;

/**
 * @member {module:model/TaskCompact} duplicated_from
 */
StoryResponseAllOf.prototype['duplicated_from'] = undefined;

/**
 * @member {module:model/TaskCompact} dependency
 */
StoryResponseAllOf.prototype['dependency'] = undefined;

/**
 * The component of the Asana product the user used to trigger the story.
 * @member {module:model/StoryResponseAllOf.SourceEnum} source
 */
StoryResponseAllOf.prototype['source'] = undefined;

/**
 * @member {module:model/TaskCompact} target
 */
StoryResponseAllOf.prototype['target'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
StoryResponseAllOf['TypeEnum'] = {

    /**
     * value: "comment"
     * @const
     */
    "comment": "comment",

    /**
     * value: "system"
     * @const
     */
    "system": "system"
};


/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
StoryResponseAllOf['SourceEnum'] = {

    /**
     * value: "web"
     * @const
     */
    "web": "web",

    /**
     * value: "email"
     * @const
     */
    "email": "email",

    /**
     * value: "mobile"
     * @const
     */
    "mobile": "mobile",

    /**
     * value: "api"
     * @const
     */
    "api": "api",

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown"
};



export default StoryResponseAllOf;

