/**
 * Asana
 * This is the interface for interacting with the Asana platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TagCompactAllOf model module.
 * @module model/TagCompactAllOf
 * @version 1.0.2
 */
class TagCompactAllOf {
    /**
     * Constructs a new <code>TagCompactAllOf</code>.
     * A *tag* is a label that can be attached to any task in Asana. It exists in a single workspace or organization.
     * @alias module:model/TagCompactAllOf
     */
    constructor() { 
        
        TagCompactAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TagCompactAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TagCompactAllOf} obj Optional instance to populate.
     * @return {module:model/TagCompactAllOf} The populated <code>TagCompactAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TagCompactAllOf();

            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} resource_type
 */
TagCompactAllOf.prototype['resource_type'] = undefined;

/**
 * Name of the tag. This is generally a short sentence fragment that fits on a line in the UI for maximum readability. However, it can be longer.
 * @member {String} name
 */
TagCompactAllOf.prototype['name'] = undefined;






export default TagCompactAllOf;

