/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskCompact from './TaskCompact';

/**
 * The TimeTrackingEntryBaseAllOf model module.
 * @module model/TimeTrackingEntryBaseAllOf
 * @version 1.0.3
 */
class TimeTrackingEntryBaseAllOf {
    /**
     * Constructs a new <code>TimeTrackingEntryBaseAllOf</code>.
     * @alias module:model/TimeTrackingEntryBaseAllOf
     */
    constructor() { 
        
        TimeTrackingEntryBaseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimeTrackingEntryBaseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeTrackingEntryBaseAllOf} obj Optional instance to populate.
     * @return {module:model/TimeTrackingEntryBaseAllOf} The populated <code>TimeTrackingEntryBaseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeTrackingEntryBaseAllOf();

            if (data.hasOwnProperty('task')) {
                obj['task'] = TaskCompact.constructFromObject(data['task']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TaskCompact} task
 */
TimeTrackingEntryBaseAllOf.prototype['task'] = undefined;

/**
 * The time at which this resource was created.
 * @member {Date} created_at
 */
TimeTrackingEntryBaseAllOf.prototype['created_at'] = undefined;






export default TimeTrackingEntryBaseAllOf;

