/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserCompact from './UserCompact';
import WorkspaceCompact from './WorkspaceCompact';

/**
 * The UserTaskListCompactAllOf model module.
 * @module model/UserTaskListCompactAllOf
 * @version 1.0.3
 */
class UserTaskListCompactAllOf {
    /**
     * Constructs a new <code>UserTaskListCompactAllOf</code>.
     * A user task list represents the tasks assigned to a particular user. It provides API access to a user’s [My Tasks](https://asana.com/guide/help/fundamentals/my-tasks) view in Asana.
     * @alias module:model/UserTaskListCompactAllOf
     */
    constructor() { 
        
        UserTaskListCompactAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserTaskListCompactAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserTaskListCompactAllOf} obj Optional instance to populate.
     * @return {module:model/UserTaskListCompactAllOf} The populated <code>UserTaskListCompactAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserTaskListCompactAllOf();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], UserCompact);
            }
            if (data.hasOwnProperty('workspace')) {
                obj['workspace'] = ApiClient.convertToType(data['workspace'], WorkspaceCompact);
            }
        }
        return obj;
    }


}

/**
 * The name of the user task list.
 * @member {String} name
 */
UserTaskListCompactAllOf.prototype['name'] = undefined;

/**
 * The owner of the user task list, i.e. the person whose My Tasks is represented by this resource.
 * @member {module:model/UserCompact} owner
 */
UserTaskListCompactAllOf.prototype['owner'] = undefined;

/**
 * The workspace in which the user task list is located.
 * @member {module:model/WorkspaceCompact} workspace
 */
UserTaskListCompactAllOf.prototype['workspace'] = undefined;






export default UserTaskListCompactAllOf;

