/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AsanaNamedResource from './AsanaNamedResource';

/**
 * The WebhookCompactAllOf model module.
 * @module model/WebhookCompactAllOf
 * @version 1.0.3
 */
class WebhookCompactAllOf {
    /**
     * Constructs a new <code>WebhookCompactAllOf</code>.
     * Webhook objects represent the state of an active subscription for a server to be updated with information from Asana. This schema represents the subscription itself, not the objects that are sent to the server. For information on those please refer to the [event](/reference/events) schema.
     * @alias module:model/WebhookCompactAllOf
     */
    constructor() { 
        
        WebhookCompactAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebhookCompactAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookCompactAllOf} obj Optional instance to populate.
     * @return {module:model/WebhookCompactAllOf} The populated <code>WebhookCompactAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookCompactAllOf();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('resource')) {
                obj['resource'] = AsanaNamedResource.constructFromObject(data['resource']);
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
        }
        return obj;
    }


}

/**
 * If true, the webhook will send events - if false it is considered inactive and will not generate events.
 * @member {Boolean} active
 */
WebhookCompactAllOf.prototype['active'] = undefined;

/**
 * @member {module:model/AsanaNamedResource} resource
 */
WebhookCompactAllOf.prototype['resource'] = undefined;

/**
 * The URL to receive the HTTP POST.
 * @member {String} target
 */
WebhookCompactAllOf.prototype['target'] = undefined;






export default WebhookCompactAllOf;

