/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddTaskForSectionRequest from '../model/AddTaskForSectionRequest';
import DeleteAttachment200Response from '../model/DeleteAttachment200Response';
import ErrorResponse from '../model/ErrorResponse';
import GetSection200Response from '../model/GetSection200Response';
import GetSectionsForProject200Response from '../model/GetSectionsForProject200Response';
import InsertSectionForProjectRequest from '../model/InsertSectionForProjectRequest';
import UpdateSectionRequest from '../model/UpdateSectionRequest';

/**
* Sections service.
* @module api/SectionsApi
* @version 1.0.4
*/
export default class SectionsApi {

    /**
    * Constructs a new SectionsApi. 
    * @alias module:api/SectionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addTaskForSection operation.
     * @callback module:api/SectionsApi~addTaskForSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteAttachment200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add task to section
     * Add a task to a specific, existing section. This will remove the task from other sections of the project.  The task will be inserted at the top of a section unless an insert_before or insert_after parameter is declared.  This does not work for separators (tasks with the resource_subtype of section).
     * @param {String} sectionGid The globally unique identifier for the section.
     * @param {module:model/AddTaskForSectionRequest} addTaskForSectionRequest The task and optionally the insert location.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {module:api/SectionsApi~addTaskForSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteAttachment200Response}
     */
    addTaskForSection(sectionGid, addTaskForSectionRequest, opts, callback) {
      opts = opts || {};
      let postBody = addTaskForSectionRequest;
      // verify the required parameter 'sectionGid' is set
      if (sectionGid === undefined || sectionGid === null) {
        throw new Error("Missing the required parameter 'sectionGid' when calling addTaskForSection");
      }
      // verify the required parameter 'addTaskForSectionRequest' is set
      if (addTaskForSectionRequest === undefined || addTaskForSectionRequest === null) {
        throw new Error("Missing the required parameter 'addTaskForSectionRequest' when calling addTaskForSection");
      }

      let pathParams = {
        'section_gid': sectionGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = ['application/json; charset=UTF-8'];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = DeleteAttachment200Response;
      return this.apiClient.callApi(
        '/sections/{section_gid}/addTask', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createSectionForProject operation.
     * @callback module:api/SectionsApi~createSectionForProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetSection200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a section in a project
     * Creates a new section in a project. Returns the full record of the newly created section.
     * @param {String} projectGid Globally unique identifier for the project.
     * @param {module:model/UpdateSectionRequest} updateSectionRequest The section to create.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array.<module:model/String>} opts.optFields This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {module:api/SectionsApi~createSectionForProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetSection200Response}
     */
    createSectionForProject(projectGid, updateSectionRequest, opts, callback) {
      opts = opts || {};
      let postBody = updateSectionRequest;
      // verify the required parameter 'projectGid' is set
      if (projectGid === undefined || projectGid === null) {
        throw new Error("Missing the required parameter 'projectGid' when calling createSectionForProject");
      }
      // verify the required parameter 'updateSectionRequest' is set
      if (updateSectionRequest === undefined || updateSectionRequest === null) {
        throw new Error("Missing the required parameter 'updateSectionRequest' when calling createSectionForProject");
      }

      let pathParams = {
        'project_gid': projectGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty'],
        'opt_fields': this.apiClient.buildCollectionParam(opts['optFields'], 'csv')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = ['application/json; charset=UTF-8'];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = GetSection200Response;
      return this.apiClient.callApi(
        '/projects/{project_gid}/sections', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSection operation.
     * @callback module:api/SectionsApi~deleteSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteAttachment200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a section
     * A specific, existing section can be deleted by making a DELETE request on the URL for that section.  Note that sections must be empty to be deleted.  The last remaining section cannot be deleted.  Returns an empty data block.
     * @param {String} sectionGid The globally unique identifier for the section.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {module:api/SectionsApi~deleteSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteAttachment200Response}
     */
    deleteSection(sectionGid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'sectionGid' is set
      if (sectionGid === undefined || sectionGid === null) {
        throw new Error("Missing the required parameter 'sectionGid' when calling deleteSection");
      }

      let pathParams = {
        'section_gid': sectionGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = [];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = DeleteAttachment200Response;
      return this.apiClient.callApi(
        '/sections/{section_gid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSection operation.
     * @callback module:api/SectionsApi~getSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetSection200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a section
     * Returns the complete record for a single section.
     * @param {String} sectionGid The globally unique identifier for the section.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array.<module:model/String>} opts.optFields This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {module:api/SectionsApi~getSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetSection200Response}
     */
    getSection(sectionGid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'sectionGid' is set
      if (sectionGid === undefined || sectionGid === null) {
        throw new Error("Missing the required parameter 'sectionGid' when calling getSection");
      }

      let pathParams = {
        'section_gid': sectionGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty'],
        'opt_fields': this.apiClient.buildCollectionParam(opts['optFields'], 'csv')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = [];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = GetSection200Response;
      return this.apiClient.callApi(
        '/sections/{section_gid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSectionsForProject operation.
     * @callback module:api/SectionsApi~getSectionsForProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetSectionsForProject200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get sections in a project
     * Returns the compact records for all sections in the specified project.
     * @param {String} projectGid Globally unique identifier for the project.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Number} opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param {String} opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
     * @param {Array.<module:model/String>} opts.optFields This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {module:api/SectionsApi~getSectionsForProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetSectionsForProject200Response}
     */
    getSectionsForProject(projectGid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'projectGid' is set
      if (projectGid === undefined || projectGid === null) {
        throw new Error("Missing the required parameter 'projectGid' when calling getSectionsForProject");
      }

      let pathParams = {
        'project_gid': projectGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'opt_fields': this.apiClient.buildCollectionParam(opts['optFields'], 'csv')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = [];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = GetSectionsForProject200Response;
      return this.apiClient.callApi(
        '/projects/{project_gid}/sections', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the insertSectionForProject operation.
     * @callback module:api/SectionsApi~insertSectionForProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteAttachment200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Move or Insert sections
     * Move sections relative to each other. One of `before_section` or `after_section` is required.  Sections cannot be moved between projects.  Returns an empty data block.
     * @param {String} projectGid Globally unique identifier for the project.
     * @param {module:model/InsertSectionForProjectRequest} insertSectionForProjectRequest The section's move action.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {module:api/SectionsApi~insertSectionForProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteAttachment200Response}
     */
    insertSectionForProject(projectGid, insertSectionForProjectRequest, opts, callback) {
      opts = opts || {};
      let postBody = insertSectionForProjectRequest;
      // verify the required parameter 'projectGid' is set
      if (projectGid === undefined || projectGid === null) {
        throw new Error("Missing the required parameter 'projectGid' when calling insertSectionForProject");
      }
      // verify the required parameter 'insertSectionForProjectRequest' is set
      if (insertSectionForProjectRequest === undefined || insertSectionForProjectRequest === null) {
        throw new Error("Missing the required parameter 'insertSectionForProjectRequest' when calling insertSectionForProject");
      }

      let pathParams = {
        'project_gid': projectGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = ['application/json; charset=UTF-8'];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = DeleteAttachment200Response;
      return this.apiClient.callApi(
        '/projects/{project_gid}/sections/insert', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSection operation.
     * @callback module:api/SectionsApi~updateSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetSection200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a section
     * A specific, existing section can be updated by making a PUT request on the URL for that project. Only the fields provided in the `data` block will be updated; any unspecified fields will remain unchanged. (note that at this time, the only field that can be updated is the `name` field.)  When using this method, it is best to specify only those fields you wish to change, or else you may overwrite changes made by another user since you last retrieved the task.  Returns the complete updated section record.
     * @param {String} sectionGid The globally unique identifier for the section.
     * @param {module:model/UpdateSectionRequest} updateSectionRequest The section to create.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.optPretty Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array.<module:model/String>} opts.optFields This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {module:api/SectionsApi~updateSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetSection200Response}
     */
    updateSection(sectionGid, updateSectionRequest, opts, callback) {
      opts = opts || {};
      let postBody = updateSectionRequest;
      // verify the required parameter 'sectionGid' is set
      if (sectionGid === undefined || sectionGid === null) {
        throw new Error("Missing the required parameter 'sectionGid' when calling updateSection");
      }
      // verify the required parameter 'updateSectionRequest' is set
      if (updateSectionRequest === undefined || updateSectionRequest === null) {
        throw new Error("Missing the required parameter 'updateSectionRequest' when calling updateSection");
      }

      let pathParams = {
        'section_gid': sectionGid
      };
      let queryParams = {
        'opt_pretty': opts['optPretty'],
        'opt_fields': this.apiClient.buildCollectionParam(opts['optFields'], 'csv')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['personalAccessToken'];
      let contentTypes = ['application/json; charset=UTF-8'];
      let accepts = ['application/json; charset=UTF-8'];
      let returnType = GetSection200Response;
      return this.apiClient.callApi(
        '/sections/{section_gid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
