/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsanaPreview);
  }
}(this, function(expect, AsanaPreview) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsanaPreview.GoalMetricRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GoalMetricRequest', function() {
    it('should create an instance of GoalMetricRequest', function() {
      // uncomment below and update the code to test GoalMetricRequest
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be.a(AsanaPreview.GoalMetricRequest);
    });

    it('should have the property gid (base name: "gid")', function() {
      // uncomment below and update the code to test the property gid
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property resourceType (base name: "resource_type")', function() {
      // uncomment below and update the code to test the property resourceType
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property resourceSubtype (base name: "resource_subtype")', function() {
      // uncomment below and update the code to test the property resourceSubtype
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property precision (base name: "precision")', function() {
      // uncomment below and update the code to test the property precision
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currency_code")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property initialNumberValue (base name: "initial_number_value")', function() {
      // uncomment below and update the code to test the property initialNumberValue
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property targetNumberValue (base name: "target_number_value")', function() {
      // uncomment below and update the code to test the property targetNumberValue
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property currentNumberValue (base name: "current_number_value")', function() {
      // uncomment below and update the code to test the property currentNumberValue
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property currentDisplayValue (base name: "current_display_value")', function() {
      // uncomment below and update the code to test the property currentDisplayValue
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

    it('should have the property progressSource (base name: "progress_source")', function() {
      // uncomment below and update the code to test the property progressSource
      //var instance = new AsanaPreview.GoalMetricRequest();
      //expect(instance).to.be();
    });

  });

}));
