/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddCustomFieldSettingForPortfolio200Response from './model/AddCustomFieldSettingForPortfolio200Response';
import AddCustomFieldSettingForPortfolioRequest from './model/AddCustomFieldSettingForPortfolioRequest';
import AddCustomFieldSettingRequest from './model/AddCustomFieldSettingRequest';
import AddDependenciesForTaskRequest from './model/AddDependenciesForTaskRequest';
import AddDependentsForTaskRequest from './model/AddDependentsForTaskRequest';
import AddFollowersForProjectRequest from './model/AddFollowersForProjectRequest';
import AddFollowersRequest from './model/AddFollowersRequest';
import AddItemForPortfolioRequest from './model/AddItemForPortfolioRequest';
import AddMembersForPortfolioRequest from './model/AddMembersForPortfolioRequest';
import AddMembersRequest from './model/AddMembersRequest';
import AddProjectForTaskRequest from './model/AddProjectForTaskRequest';
import AddSupportingRelationshipRequest from './model/AddSupportingRelationshipRequest';
import AddTagForTaskRequest from './model/AddTagForTaskRequest';
import AddTaskForSectionRequest from './model/AddTaskForSectionRequest';
import AddUserForTeamRequest from './model/AddUserForTeamRequest';
import AddUserForWorkspace200Response from './model/AddUserForWorkspace200Response';
import AddUserForWorkspaceRequest from './model/AddUserForWorkspaceRequest';
import AsanaNamedResource from './model/AsanaNamedResource';
import AsanaResource from './model/AsanaResource';
import AttachmentBase from './model/AttachmentBase';
import AttachmentCompact from './model/AttachmentCompact';
import AttachmentResponse from './model/AttachmentResponse';
import AttachmentResponseParent from './model/AttachmentResponseParent';
import AuditLogEvent from './model/AuditLogEvent';
import AuditLogEventActor from './model/AuditLogEventActor';
import AuditLogEventContext from './model/AuditLogEventContext';
import AuditLogEventResource from './model/AuditLogEventResource';
import BatchRequest from './model/BatchRequest';
import BatchRequestAction from './model/BatchRequestAction';
import BatchRequestActionsInner from './model/BatchRequestActionsInner';
import BatchRequestActionsInnerOptions from './model/BatchRequestActionsInnerOptions';
import BatchResponse from './model/BatchResponse';
import CreateBatchRequest200Response from './model/CreateBatchRequest200Response';
import CreateBatchRequestRequest from './model/CreateBatchRequestRequest';
import CreateCustomField201Response from './model/CreateCustomField201Response';
import CreateCustomFieldRequest from './model/CreateCustomFieldRequest';
import CreateEnumOptionForCustomField201Response from './model/CreateEnumOptionForCustomField201Response';
import CreateEnumOptionForCustomFieldRequest from './model/CreateEnumOptionForCustomFieldRequest';
import CreateGoalMetricRequest from './model/CreateGoalMetricRequest';
import CreateMembership200Response from './model/CreateMembership200Response';
import CreateMembershipRequest from './model/CreateMembershipRequest';
import CreateOrganizationExport201Response from './model/CreateOrganizationExport201Response';
import CreateOrganizationExportRequest from './model/CreateOrganizationExportRequest';
import CreatePortfolio201Response from './model/CreatePortfolio201Response';
import CreatePortfolioRequest from './model/CreatePortfolioRequest';
import CreateProject201Response from './model/CreateProject201Response';
import CreateProjectFromAsanaTemplateRequest from './model/CreateProjectFromAsanaTemplateRequest';
import CreateProjectFromAsanaTemplateRequestAllOf from './model/CreateProjectFromAsanaTemplateRequestAllOf';
import CreateProjectFromAsanaTemplateRequestAllOf1 from './model/CreateProjectFromAsanaTemplateRequestAllOf1';
import CreateProjectFromAsanaTemplateRequestAllOf1Workspace from './model/CreateProjectFromAsanaTemplateRequestAllOf1Workspace';
import CreateProjectRequest from './model/CreateProjectRequest';
import CreateProjectStatusForProjectRequest from './model/CreateProjectStatusForProjectRequest';
import CreateStatusForObjectRequest from './model/CreateStatusForObjectRequest';
import CreateTag201Response from './model/CreateTag201Response';
import CreateTagRequest from './model/CreateTagRequest';
import CreateTask201Response from './model/CreateTask201Response';
import CreateTaskRequest from './model/CreateTaskRequest';
import CreateTimeTrackingEntry201Response from './model/CreateTimeTrackingEntry201Response';
import CreateTimeTrackingEntryRequest from './model/CreateTimeTrackingEntryRequest';
import CreateWebhook201Response from './model/CreateWebhook201Response';
import CreateWebhookRequest from './model/CreateWebhookRequest';
import CustomFieldBase from './model/CustomFieldBase';
import CustomFieldBaseDateValue from './model/CustomFieldBaseDateValue';
import CustomFieldBaseEnumOptionsInner from './model/CustomFieldBaseEnumOptionsInner';
import CustomFieldBaseEnumValue from './model/CustomFieldBaseEnumValue';
import CustomFieldCompact from './model/CustomFieldCompact';
import CustomFieldRequest from './model/CustomFieldRequest';
import CustomFieldResponse from './model/CustomFieldResponse';
import CustomFieldResponseCreatedBy from './model/CustomFieldResponseCreatedBy';
import CustomFieldResponsePeopleValueInner from './model/CustomFieldResponsePeopleValueInner';
import CustomFieldSettingBase from './model/CustomFieldSettingBase';
import CustomFieldSettingCompact from './model/CustomFieldSettingCompact';
import CustomFieldSettingResponse from './model/CustomFieldSettingResponse';
import CustomFieldSettingResponseCustomField from './model/CustomFieldSettingResponseCustomField';
import CustomFieldSettingResponseParent from './model/CustomFieldSettingResponseParent';
import CustomFieldSettingResponseProject from './model/CustomFieldSettingResponseProject';
import DateVariableCompact from './model/DateVariableCompact';
import DateVariableRequest from './model/DateVariableRequest';
import DeleteAttachment200Response from './model/DeleteAttachment200Response';
import DuplicateProjectRequest from './model/DuplicateProjectRequest';
import DuplicateTaskRequest from './model/DuplicateTaskRequest';
import EnumOption from './model/EnumOption';
import EnumOptionBase from './model/EnumOptionBase';
import EnumOptionInsertRequest from './model/EnumOptionInsertRequest';
import EnumOptionRequest from './model/EnumOptionRequest';
import Error from './model/Error';
import ErrorResponse from './model/ErrorResponse';
import ErrorResponseErrorsInner from './model/ErrorResponseErrorsInner';
import EventResponse from './model/EventResponse';
import EventResponseChange from './model/EventResponseChange';
import EventResponseParent from './model/EventResponseParent';
import EventResponseResource from './model/EventResponseResource';
import EventResponseUser from './model/EventResponseUser';
import GetAttachment200Response from './model/GetAttachment200Response';
import GetAttachmentsForObject200Response from './model/GetAttachmentsForObject200Response';
import GetAuditLogEvents200Response from './model/GetAuditLogEvents200Response';
import GetCustomFieldSettingsForProject200Response from './model/GetCustomFieldSettingsForProject200Response';
import GetCustomFieldsForWorkspace200Response from './model/GetCustomFieldsForWorkspace200Response';
import GetEvents200Response from './model/GetEvents200Response';
import GetFavoritesForUser200Response from './model/GetFavoritesForUser200Response';
import GetGoal200Response from './model/GetGoal200Response';
import GetGoalRelationship200Response from './model/GetGoalRelationship200Response';
import GetGoalRelationships200Response from './model/GetGoalRelationships200Response';
import GetGoals200Response from './model/GetGoals200Response';
import GetItemsForPortfolio200Response from './model/GetItemsForPortfolio200Response';
import GetJob200Response from './model/GetJob200Response';
import GetMemberships200Response from './model/GetMemberships200Response';
import GetPortfolioMembership200Response from './model/GetPortfolioMembership200Response';
import GetPortfolioMemberships200Response from './model/GetPortfolioMemberships200Response';
import GetPortfolios200Response from './model/GetPortfolios200Response';
import GetProjectBrief200Response from './model/GetProjectBrief200Response';
import GetProjectMembership200Response from './model/GetProjectMembership200Response';
import GetProjectMembershipsForProject200Response from './model/GetProjectMembershipsForProject200Response';
import GetProjectStatus200Response from './model/GetProjectStatus200Response';
import GetProjectStatusesForProject200Response from './model/GetProjectStatusesForProject200Response';
import GetProjectTemplate200Response from './model/GetProjectTemplate200Response';
import GetProjectTemplates200Response from './model/GetProjectTemplates200Response';
import GetSection200Response from './model/GetSection200Response';
import GetSectionsForProject200Response from './model/GetSectionsForProject200Response';
import GetStatus200Response from './model/GetStatus200Response';
import GetStatusesForObject200Response from './model/GetStatusesForObject200Response';
import GetStoriesForTask200Response from './model/GetStoriesForTask200Response';
import GetStory200Response from './model/GetStory200Response';
import GetTags200Response from './model/GetTags200Response';
import GetTaskCountsForProject200Response from './model/GetTaskCountsForProject200Response';
import GetTasks200Response from './model/GetTasks200Response';
import GetTeamMembership200Response from './model/GetTeamMembership200Response';
import GetTeamMemberships200Response from './model/GetTeamMemberships200Response';
import GetTeamsForWorkspace200Response from './model/GetTeamsForWorkspace200Response';
import GetTimePeriod200Response from './model/GetTimePeriod200Response';
import GetTimePeriods200Response from './model/GetTimePeriods200Response';
import GetTimeTrackingEntriesForTask200Response from './model/GetTimeTrackingEntriesForTask200Response';
import GetUser200Response from './model/GetUser200Response';
import GetUserTaskList200Response from './model/GetUserTaskList200Response';
import GetUsers200Response from './model/GetUsers200Response';
import GetWebhooks200Response from './model/GetWebhooks200Response';
import GetWorkspace200Response from './model/GetWorkspace200Response';
import GetWorkspaceMembership200Response from './model/GetWorkspaceMembership200Response';
import GetWorkspaceMembershipsForUser200Response from './model/GetWorkspaceMembershipsForUser200Response';
import GetWorkspaces200Response from './model/GetWorkspaces200Response';
import GoalAddSubgoalRequest from './model/GoalAddSubgoalRequest';
import GoalAddSupportingRelationshipRequest from './model/GoalAddSupportingRelationshipRequest';
import GoalAddSupportingWorkRequest from './model/GoalAddSupportingWorkRequest';
import GoalBase from './model/GoalBase';
import GoalCompact from './model/GoalCompact';
import GoalMembershipBase from './model/GoalMembershipBase';
import GoalMembershipBaseGoal from './model/GoalMembershipBaseGoal';
import GoalMembershipCompact from './model/GoalMembershipCompact';
import GoalMembershipResponse from './model/GoalMembershipResponse';
import GoalMetricBase from './model/GoalMetricBase';
import GoalMetricCurrentValueRequest from './model/GoalMetricCurrentValueRequest';
import GoalMetricRequest from './model/GoalMetricRequest';
import GoalRelationshipBase from './model/GoalRelationshipBase';
import GoalRelationshipBaseSupportedGoal from './model/GoalRelationshipBaseSupportedGoal';
import GoalRelationshipBaseSupportingResource from './model/GoalRelationshipBaseSupportingResource';
import GoalRelationshipCompact from './model/GoalRelationshipCompact';
import GoalRelationshipRequest from './model/GoalRelationshipRequest';
import GoalRelationshipResponse from './model/GoalRelationshipResponse';
import GoalRemoveSubgoalRequest from './model/GoalRemoveSubgoalRequest';
import GoalRemoveSupportingRelationshipRequest from './model/GoalRemoveSupportingRelationshipRequest';
import GoalRequest from './model/GoalRequest';
import GoalResponse from './model/GoalResponse';
import GoalResponseCurrentStatusUpdate from './model/GoalResponseCurrentStatusUpdate';
import GoalResponseCurrentStatusUpdateAllOf from './model/GoalResponseCurrentStatusUpdateAllOf';
import GoalResponseLikesInner from './model/GoalResponseLikesInner';
import GoalResponseMetric from './model/GoalResponseMetric';
import GoalResponseTeam from './model/GoalResponseTeam';
import GoalResponseTeamAllOf from './model/GoalResponseTeamAllOf';
import GoalResponseTimePeriod from './model/GoalResponseTimePeriod';
import GoalResponseWorkspace from './model/GoalResponseWorkspace';
import InsertEnumOptionForCustomFieldRequest from './model/InsertEnumOptionForCustomFieldRequest';
import InsertSectionForProjectRequest from './model/InsertSectionForProjectRequest';
import InstantiateProjectRequest from './model/InstantiateProjectRequest';
import JobBase from './model/JobBase';
import JobBaseNewProject from './model/JobBaseNewProject';
import JobBaseNewProjectTemplate from './model/JobBaseNewProjectTemplate';
import JobBaseNewTask from './model/JobBaseNewTask';
import JobBaseNewTaskTemplate from './model/JobBaseNewTaskTemplate';
import JobBaseNewTaskTemplateAllOf from './model/JobBaseNewTaskTemplateAllOf';
import JobCompact from './model/JobCompact';
import JobResponse from './model/JobResponse';
import Like from './model/Like';
import MemberCompact from './model/MemberCompact';
import MembershipRequest from './model/MembershipRequest';
import MembershipResponse from './model/MembershipResponse';
import MembershipResponseAnyOf from './model/MembershipResponseAnyOf';
import MembershipResponseAnyOf1 from './model/MembershipResponseAnyOf1';
import MembershipResponseAnyOf2 from './model/MembershipResponseAnyOf2';
import MembershipResponseAnyOf3 from './model/MembershipResponseAnyOf3';
import MembershipResponseAnyOf4 from './model/MembershipResponseAnyOf4';
import MembershipResponseAnyOf4UserTaskList from './model/MembershipResponseAnyOf4UserTaskList';
import MessageBase from './model/MessageBase';
import MessageBaseAllOf from './model/MessageBaseAllOf';
import MessageParent from './model/MessageParent';
import MessageParentAllOf from './model/MessageParentAllOf';
import ModifyDependenciesRequest from './model/ModifyDependenciesRequest';
import ModifyDependentsRequest from './model/ModifyDependentsRequest';
import OrganizationExportBase from './model/OrganizationExportBase';
import OrganizationExportCompact from './model/OrganizationExportCompact';
import OrganizationExportRequest from './model/OrganizationExportRequest';
import OrganizationExportResponse from './model/OrganizationExportResponse';
import PortfolioAddItemRequest from './model/PortfolioAddItemRequest';
import PortfolioBase from './model/PortfolioBase';
import PortfolioCompact from './model/PortfolioCompact';
import PortfolioMembershipBase from './model/PortfolioMembershipBase';
import PortfolioMembershipBasePortfolio from './model/PortfolioMembershipBasePortfolio';
import PortfolioMembershipCompact from './model/PortfolioMembershipCompact';
import PortfolioMembershipResponse from './model/PortfolioMembershipResponse';
import PortfolioRemoveItemRequest from './model/PortfolioRemoveItemRequest';
import PortfolioRequest from './model/PortfolioRequest';
import PortfolioResponse from './model/PortfolioResponse';
import PortfolioResponseCurrentStatusUpdate from './model/PortfolioResponseCurrentStatusUpdate';
import PortfolioResponseCustomFieldSettingsInner from './model/PortfolioResponseCustomFieldSettingsInner';
import PortfolioResponseCustomFieldsInner from './model/PortfolioResponseCustomFieldsInner';
import PortfolioResponseWorkspace from './model/PortfolioResponseWorkspace';
import Preview from './model/Preview';
import ProjectBase from './model/ProjectBase';
import ProjectBaseCurrentStatus from './model/ProjectBaseCurrentStatus';
import ProjectBaseCurrentStatusAllOf from './model/ProjectBaseCurrentStatusAllOf';
import ProjectBaseCurrentStatusUpdate from './model/ProjectBaseCurrentStatusUpdate';
import ProjectBriefBase from './model/ProjectBriefBase';
import ProjectBriefCompact from './model/ProjectBriefCompact';
import ProjectBriefRequest from './model/ProjectBriefRequest';
import ProjectBriefResponse from './model/ProjectBriefResponse';
import ProjectBriefResponseProject from './model/ProjectBriefResponseProject';
import ProjectCompact from './model/ProjectCompact';
import ProjectDuplicateRequest from './model/ProjectDuplicateRequest';
import ProjectDuplicateRequestScheduleDates from './model/ProjectDuplicateRequestScheduleDates';
import ProjectMembershipBase from './model/ProjectMembershipBase';
import ProjectMembershipCompact from './model/ProjectMembershipCompact';
import ProjectMembershipResponse from './model/ProjectMembershipResponse';
import ProjectMembershipResponseMember from './model/ProjectMembershipResponseMember';
import ProjectRequest from './model/ProjectRequest';
import ProjectResponse from './model/ProjectResponse';
import ProjectResponseCompletedBy from './model/ProjectResponseCompletedBy';
import ProjectResponseCreatedFromTemplate from './model/ProjectResponseCreatedFromTemplate';
import ProjectResponseOwner from './model/ProjectResponseOwner';
import ProjectResponseProjectBrief from './model/ProjectResponseProjectBrief';
import ProjectResponseTeam from './model/ProjectResponseTeam';
import ProjectSaveAsTemplateRequest from './model/ProjectSaveAsTemplateRequest';
import ProjectSectionInsertRequest from './model/ProjectSectionInsertRequest';
import ProjectStatusBase from './model/ProjectStatusBase';
import ProjectStatusCompact from './model/ProjectStatusCompact';
import ProjectStatusRequest from './model/ProjectStatusRequest';
import ProjectStatusResponse from './model/ProjectStatusResponse';
import ProjectTemplateBase from './model/ProjectTemplateBase';
import ProjectTemplateBaseOwner from './model/ProjectTemplateBaseOwner';
import ProjectTemplateBaseRequestedDatesInner from './model/ProjectTemplateBaseRequestedDatesInner';
import ProjectTemplateBaseRequestedRolesInner from './model/ProjectTemplateBaseRequestedRolesInner';
import ProjectTemplateCompact from './model/ProjectTemplateCompact';
import ProjectTemplateInstantiateProjectRequest from './model/ProjectTemplateInstantiateProjectRequest';
import ProjectTemplateInstantiateProjectRequestRequestedDatesInner from './model/ProjectTemplateInstantiateProjectRequestRequestedDatesInner';
import ProjectTemplateInstantiateProjectRequestRequestedRolesInner from './model/ProjectTemplateInstantiateProjectRequestRequestedRolesInner';
import ProjectTemplateResponse from './model/ProjectTemplateResponse';
import RemoveCustomFieldSettingForPortfolioRequest from './model/RemoveCustomFieldSettingForPortfolioRequest';
import RemoveCustomFieldSettingRequest from './model/RemoveCustomFieldSettingRequest';
import RemoveFollowerForTaskRequest from './model/RemoveFollowerForTaskRequest';
import RemoveFollowersForProjectRequest from './model/RemoveFollowersForProjectRequest';
import RemoveFollowersRequest from './model/RemoveFollowersRequest';
import RemoveItemForPortfolioRequest from './model/RemoveItemForPortfolioRequest';
import RemoveMembersForPortfolioRequest from './model/RemoveMembersForPortfolioRequest';
import RemoveMembersRequest from './model/RemoveMembersRequest';
import RemoveProjectForTaskRequest from './model/RemoveProjectForTaskRequest';
import RemoveSupportingRelationshipRequest from './model/RemoveSupportingRelationshipRequest';
import RemoveTagForTaskRequest from './model/RemoveTagForTaskRequest';
import RemoveUserForTeamRequest from './model/RemoveUserForTeamRequest';
import RemoveUserForWorkspaceRequest from './model/RemoveUserForWorkspaceRequest';
import RequestedRoleRequest from './model/RequestedRoleRequest';
import RuleTriggerRequest from './model/RuleTriggerRequest';
import RuleTriggerResponse from './model/RuleTriggerResponse';
import ScimUser from './model/ScimUser';
import SectionBase from './model/SectionBase';
import SectionCompact from './model/SectionCompact';
import SectionRequest from './model/SectionRequest';
import SectionResponse from './model/SectionResponse';
import SectionTaskInsertRequest from './model/SectionTaskInsertRequest';
import SetParentForTaskRequest from './model/SetParentForTaskRequest';
import StatusUpdateBase from './model/StatusUpdateBase';
import StatusUpdateCompact from './model/StatusUpdateCompact';
import StatusUpdateRequest from './model/StatusUpdateRequest';
import StatusUpdateResponse from './model/StatusUpdateResponse';
import StatusUpdateResponseParent from './model/StatusUpdateResponseParent';
import StoryBase from './model/StoryBase';
import StoryCompact from './model/StoryCompact';
import StoryRequest from './model/StoryRequest';
import StoryResponse from './model/StoryResponse';
import StoryResponseAssignee from './model/StoryResponseAssignee';
import StoryResponseCustomField from './model/StoryResponseCustomField';
import StoryResponseDates from './model/StoryResponseDates';
import StoryResponseNewDateValue from './model/StoryResponseNewDateValue';
import StoryResponseOldDateValue from './model/StoryResponseOldDateValue';
import StoryResponseOldDates from './model/StoryResponseOldDates';
import StoryResponseOldEnumValue from './model/StoryResponseOldEnumValue';
import StoryResponseOldSection from './model/StoryResponseOldSection';
import StoryResponsePreviewsInner from './model/StoryResponsePreviewsInner';
import StoryResponseProject from './model/StoryResponseProject';
import StoryResponseStory from './model/StoryResponseStory';
import StoryResponseTag from './model/StoryResponseTag';
import StoryResponseTarget from './model/StoryResponseTarget';
import StoryResponseTask from './model/StoryResponseTask';
import TagBase from './model/TagBase';
import TagCompact from './model/TagCompact';
import TagRequest from './model/TagRequest';
import TagResponse from './model/TagResponse';
import TaskAddFollowersRequest from './model/TaskAddFollowersRequest';
import TaskAddProjectRequest from './model/TaskAddProjectRequest';
import TaskAddTagRequest from './model/TaskAddTagRequest';
import TaskBase from './model/TaskBase';
import TaskBaseExternal from './model/TaskBaseExternal';
import TaskBaseMembershipsInner from './model/TaskBaseMembershipsInner';
import TaskBaseMembershipsInnerSection from './model/TaskBaseMembershipsInnerSection';
import TaskCompact from './model/TaskCompact';
import TaskConvertToTemplateRequest from './model/TaskConvertToTemplateRequest';
import TaskCountResponse from './model/TaskCountResponse';
import TaskDuplicateRequest from './model/TaskDuplicateRequest';
import TaskRemoveFollowersRequest from './model/TaskRemoveFollowersRequest';
import TaskRemoveProjectRequest from './model/TaskRemoveProjectRequest';
import TaskRemoveTagRequest from './model/TaskRemoveTagRequest';
import TaskRequest from './model/TaskRequest';
import TaskResponse from './model/TaskResponse';
import TaskResponseAssignee from './model/TaskResponseAssignee';
import TaskResponseAssigneeSection from './model/TaskResponseAssigneeSection';
import TaskResponseCustomFieldsInner from './model/TaskResponseCustomFieldsInner';
import TaskResponseParent from './model/TaskResponseParent';
import TaskResponseTagsInner from './model/TaskResponseTagsInner';
import TaskResponseWorkspace from './model/TaskResponseWorkspace';
import TaskSetParentRequest from './model/TaskSetParentRequest';
import TaskTemplateCompact from './model/TaskTemplateCompact';
import TaskTemplateInstantiateTaskRequest from './model/TaskTemplateInstantiateTaskRequest';
import TeamAddUserRequest from './model/TeamAddUserRequest';
import TeamBase from './model/TeamBase';
import TeamCompact from './model/TeamCompact';
import TeamMembershipBase from './model/TeamMembershipBase';
import TeamMembershipCompact from './model/TeamMembershipCompact';
import TeamMembershipResponse from './model/TeamMembershipResponse';
import TeamRemoveUserRequest from './model/TeamRemoveUserRequest';
import TeamRequest from './model/TeamRequest';
import TeamResponse from './model/TeamResponse';
import TeamResponseOrganization from './model/TeamResponseOrganization';
import TemplateRole from './model/TemplateRole';
import TimePeriodBase from './model/TimePeriodBase';
import TimePeriodBaseParent from './model/TimePeriodBaseParent';
import TimePeriodCompact from './model/TimePeriodCompact';
import TimePeriodResponse from './model/TimePeriodResponse';
import TimeTrackingEntryBase from './model/TimeTrackingEntryBase';
import TimeTrackingEntryCompact from './model/TimeTrackingEntryCompact';
import TriggerRule200Response from './model/TriggerRule200Response';
import TriggerRuleRequest from './model/TriggerRuleRequest';
import TypeaheadForWorkspace200Response from './model/TypeaheadForWorkspace200Response';
import UpdateGoalMetricRequest from './model/UpdateGoalMetricRequest';
import UpdateGoalRelationshipRequest from './model/UpdateGoalRelationshipRequest';
import UpdateGoalRequest from './model/UpdateGoalRequest';
import UpdateMembershipRequest from './model/UpdateMembershipRequest';
import UpdateProjectBriefRequest from './model/UpdateProjectBriefRequest';
import UpdateSectionRequest from './model/UpdateSectionRequest';
import UpdateStoryRequest from './model/UpdateStoryRequest';
import UpdateTeam200Response from './model/UpdateTeam200Response';
import UpdateTeamRequest from './model/UpdateTeamRequest';
import UpdateTimeTrackingEntryRequest from './model/UpdateTimeTrackingEntryRequest';
import UpdateWebhookRequest from './model/UpdateWebhookRequest';
import UpdateWorkspaceRequest from './model/UpdateWorkspaceRequest';
import UserBase from './model/UserBase';
import UserBaseResponse from './model/UserBaseResponse';
import UserBaseResponsePhoto from './model/UserBaseResponsePhoto';
import UserCompact from './model/UserCompact';
import UserRequest from './model/UserRequest';
import UserResponse from './model/UserResponse';
import UserTaskListBase from './model/UserTaskListBase';
import UserTaskListBaseOwner from './model/UserTaskListBaseOwner';
import UserTaskListBaseWorkspace from './model/UserTaskListBaseWorkspace';
import UserTaskListCompact from './model/UserTaskListCompact';
import UserTaskListRequest from './model/UserTaskListRequest';
import UserTaskListResponse from './model/UserTaskListResponse';
import WebhookCompact from './model/WebhookCompact';
import WebhookFilter from './model/WebhookFilter';
import WebhookRequest from './model/WebhookRequest';
import WebhookRequestFiltersInner from './model/WebhookRequestFiltersInner';
import WebhookResponse from './model/WebhookResponse';
import WebhookUpdateRequest from './model/WebhookUpdateRequest';
import WorkspaceAddUserRequest from './model/WorkspaceAddUserRequest';
import WorkspaceBase from './model/WorkspaceBase';
import WorkspaceCompact from './model/WorkspaceCompact';
import WorkspaceEventResponse from './model/WorkspaceEventResponse';
import WorkspaceEventResponseAllOf from './model/WorkspaceEventResponseAllOf';
import WorkspaceMembershipBase from './model/WorkspaceMembershipBase';
import WorkspaceMembershipCompact from './model/WorkspaceMembershipCompact';
import WorkspaceMembershipRequest from './model/WorkspaceMembershipRequest';
import WorkspaceMembershipResponse from './model/WorkspaceMembershipResponse';
import WorkspaceMembershipResponseUserTaskList from './model/WorkspaceMembershipResponseUserTaskList';
import WorkspaceMembershipResponseVacationDates from './model/WorkspaceMembershipResponseVacationDates';
import WorkspaceRemoveUserRequest from './model/WorkspaceRemoveUserRequest';
import WorkspaceRequest from './model/WorkspaceRequest';
import WorkspaceResponse from './model/WorkspaceResponse';
import AttachmentsApi from './api/AttachmentsApi';
import AuditLogAPIApi from './api/AuditLogAPIApi';
import BatchAPIApi from './api/BatchAPIApi';
import CustomFieldSettingsApi from './api/CustomFieldSettingsApi';
import CustomFieldsApi from './api/CustomFieldsApi';
import EventsApi from './api/EventsApi';
import GoalRelationshipsApi from './api/GoalRelationshipsApi';
import GoalsApi from './api/GoalsApi';
import JobsApi from './api/JobsApi';
import MembershipsApi from './api/MembershipsApi';
import OrganizationExportsApi from './api/OrganizationExportsApi';
import PortfolioMembershipsApi from './api/PortfolioMembershipsApi';
import PortfoliosApi from './api/PortfoliosApi';
import ProjectBriefsApi from './api/ProjectBriefsApi';
import ProjectMembershipsApi from './api/ProjectMembershipsApi';
import ProjectStatusesApi from './api/ProjectStatusesApi';
import ProjectTemplatesApi from './api/ProjectTemplatesApi';
import ProjectsApi from './api/ProjectsApi';
import RulesApi from './api/RulesApi';
import SectionsApi from './api/SectionsApi';
import StatusUpdatesApi from './api/StatusUpdatesApi';
import StoriesApi from './api/StoriesApi';
import TagsApi from './api/TagsApi';
import TasksApi from './api/TasksApi';
import TeamMembershipsApi from './api/TeamMembershipsApi';
import TeamsApi from './api/TeamsApi';
import TimePeriodsApi from './api/TimePeriodsApi';
import TimeTrackingEntriesApi from './api/TimeTrackingEntriesApi';
import TypeaheadApi from './api/TypeaheadApi';
import UserTaskListsApi from './api/UserTaskListsApi';
import UsersApi from './api/UsersApi';
import WebhooksApi from './api/WebhooksApi';
import WorkspaceMembershipsApi from './api/WorkspaceMembershipsApi';
import WorkspacesApi from './api/WorkspacesApi';


/**
* This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml)..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AsanaPreview = require('index'); // See note below*.
* var xxxSvc = new AsanaPreview.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AsanaPreview.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AsanaPreview.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AsanaPreview.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.4
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddCustomFieldSettingForPortfolio200Response model constructor.
     * @property {module:model/AddCustomFieldSettingForPortfolio200Response}
     */
    AddCustomFieldSettingForPortfolio200Response,

    /**
     * The AddCustomFieldSettingForPortfolioRequest model constructor.
     * @property {module:model/AddCustomFieldSettingForPortfolioRequest}
     */
    AddCustomFieldSettingForPortfolioRequest,

    /**
     * The AddCustomFieldSettingRequest model constructor.
     * @property {module:model/AddCustomFieldSettingRequest}
     */
    AddCustomFieldSettingRequest,

    /**
     * The AddDependenciesForTaskRequest model constructor.
     * @property {module:model/AddDependenciesForTaskRequest}
     */
    AddDependenciesForTaskRequest,

    /**
     * The AddDependentsForTaskRequest model constructor.
     * @property {module:model/AddDependentsForTaskRequest}
     */
    AddDependentsForTaskRequest,

    /**
     * The AddFollowersForProjectRequest model constructor.
     * @property {module:model/AddFollowersForProjectRequest}
     */
    AddFollowersForProjectRequest,

    /**
     * The AddFollowersRequest model constructor.
     * @property {module:model/AddFollowersRequest}
     */
    AddFollowersRequest,

    /**
     * The AddItemForPortfolioRequest model constructor.
     * @property {module:model/AddItemForPortfolioRequest}
     */
    AddItemForPortfolioRequest,

    /**
     * The AddMembersForPortfolioRequest model constructor.
     * @property {module:model/AddMembersForPortfolioRequest}
     */
    AddMembersForPortfolioRequest,

    /**
     * The AddMembersRequest model constructor.
     * @property {module:model/AddMembersRequest}
     */
    AddMembersRequest,

    /**
     * The AddProjectForTaskRequest model constructor.
     * @property {module:model/AddProjectForTaskRequest}
     */
    AddProjectForTaskRequest,

    /**
     * The AddSupportingRelationshipRequest model constructor.
     * @property {module:model/AddSupportingRelationshipRequest}
     */
    AddSupportingRelationshipRequest,

    /**
     * The AddTagForTaskRequest model constructor.
     * @property {module:model/AddTagForTaskRequest}
     */
    AddTagForTaskRequest,

    /**
     * The AddTaskForSectionRequest model constructor.
     * @property {module:model/AddTaskForSectionRequest}
     */
    AddTaskForSectionRequest,

    /**
     * The AddUserForTeamRequest model constructor.
     * @property {module:model/AddUserForTeamRequest}
     */
    AddUserForTeamRequest,

    /**
     * The AddUserForWorkspace200Response model constructor.
     * @property {module:model/AddUserForWorkspace200Response}
     */
    AddUserForWorkspace200Response,

    /**
     * The AddUserForWorkspaceRequest model constructor.
     * @property {module:model/AddUserForWorkspaceRequest}
     */
    AddUserForWorkspaceRequest,

    /**
     * The AsanaNamedResource model constructor.
     * @property {module:model/AsanaNamedResource}
     */
    AsanaNamedResource,

    /**
     * The AsanaResource model constructor.
     * @property {module:model/AsanaResource}
     */
    AsanaResource,

    /**
     * The AttachmentBase model constructor.
     * @property {module:model/AttachmentBase}
     */
    AttachmentBase,

    /**
     * The AttachmentCompact model constructor.
     * @property {module:model/AttachmentCompact}
     */
    AttachmentCompact,

    /**
     * The AttachmentResponse model constructor.
     * @property {module:model/AttachmentResponse}
     */
    AttachmentResponse,

    /**
     * The AttachmentResponseParent model constructor.
     * @property {module:model/AttachmentResponseParent}
     */
    AttachmentResponseParent,

    /**
     * The AuditLogEvent model constructor.
     * @property {module:model/AuditLogEvent}
     */
    AuditLogEvent,

    /**
     * The AuditLogEventActor model constructor.
     * @property {module:model/AuditLogEventActor}
     */
    AuditLogEventActor,

    /**
     * The AuditLogEventContext model constructor.
     * @property {module:model/AuditLogEventContext}
     */
    AuditLogEventContext,

    /**
     * The AuditLogEventResource model constructor.
     * @property {module:model/AuditLogEventResource}
     */
    AuditLogEventResource,

    /**
     * The BatchRequest model constructor.
     * @property {module:model/BatchRequest}
     */
    BatchRequest,

    /**
     * The BatchRequestAction model constructor.
     * @property {module:model/BatchRequestAction}
     */
    BatchRequestAction,

    /**
     * The BatchRequestActionsInner model constructor.
     * @property {module:model/BatchRequestActionsInner}
     */
    BatchRequestActionsInner,

    /**
     * The BatchRequestActionsInnerOptions model constructor.
     * @property {module:model/BatchRequestActionsInnerOptions}
     */
    BatchRequestActionsInnerOptions,

    /**
     * The BatchResponse model constructor.
     * @property {module:model/BatchResponse}
     */
    BatchResponse,

    /**
     * The CreateBatchRequest200Response model constructor.
     * @property {module:model/CreateBatchRequest200Response}
     */
    CreateBatchRequest200Response,

    /**
     * The CreateBatchRequestRequest model constructor.
     * @property {module:model/CreateBatchRequestRequest}
     */
    CreateBatchRequestRequest,

    /**
     * The CreateCustomField201Response model constructor.
     * @property {module:model/CreateCustomField201Response}
     */
    CreateCustomField201Response,

    /**
     * The CreateCustomFieldRequest model constructor.
     * @property {module:model/CreateCustomFieldRequest}
     */
    CreateCustomFieldRequest,

    /**
     * The CreateEnumOptionForCustomField201Response model constructor.
     * @property {module:model/CreateEnumOptionForCustomField201Response}
     */
    CreateEnumOptionForCustomField201Response,

    /**
     * The CreateEnumOptionForCustomFieldRequest model constructor.
     * @property {module:model/CreateEnumOptionForCustomFieldRequest}
     */
    CreateEnumOptionForCustomFieldRequest,

    /**
     * The CreateGoalMetricRequest model constructor.
     * @property {module:model/CreateGoalMetricRequest}
     */
    CreateGoalMetricRequest,

    /**
     * The CreateMembership200Response model constructor.
     * @property {module:model/CreateMembership200Response}
     */
    CreateMembership200Response,

    /**
     * The CreateMembershipRequest model constructor.
     * @property {module:model/CreateMembershipRequest}
     */
    CreateMembershipRequest,

    /**
     * The CreateOrganizationExport201Response model constructor.
     * @property {module:model/CreateOrganizationExport201Response}
     */
    CreateOrganizationExport201Response,

    /**
     * The CreateOrganizationExportRequest model constructor.
     * @property {module:model/CreateOrganizationExportRequest}
     */
    CreateOrganizationExportRequest,

    /**
     * The CreatePortfolio201Response model constructor.
     * @property {module:model/CreatePortfolio201Response}
     */
    CreatePortfolio201Response,

    /**
     * The CreatePortfolioRequest model constructor.
     * @property {module:model/CreatePortfolioRequest}
     */
    CreatePortfolioRequest,

    /**
     * The CreateProject201Response model constructor.
     * @property {module:model/CreateProject201Response}
     */
    CreateProject201Response,

    /**
     * The CreateProjectFromAsanaTemplateRequest model constructor.
     * @property {module:model/CreateProjectFromAsanaTemplateRequest}
     */
    CreateProjectFromAsanaTemplateRequest,

    /**
     * The CreateProjectFromAsanaTemplateRequestAllOf model constructor.
     * @property {module:model/CreateProjectFromAsanaTemplateRequestAllOf}
     */
    CreateProjectFromAsanaTemplateRequestAllOf,

    /**
     * The CreateProjectFromAsanaTemplateRequestAllOf1 model constructor.
     * @property {module:model/CreateProjectFromAsanaTemplateRequestAllOf1}
     */
    CreateProjectFromAsanaTemplateRequestAllOf1,

    /**
     * The CreateProjectFromAsanaTemplateRequestAllOf1Workspace model constructor.
     * @property {module:model/CreateProjectFromAsanaTemplateRequestAllOf1Workspace}
     */
    CreateProjectFromAsanaTemplateRequestAllOf1Workspace,

    /**
     * The CreateProjectRequest model constructor.
     * @property {module:model/CreateProjectRequest}
     */
    CreateProjectRequest,

    /**
     * The CreateProjectStatusForProjectRequest model constructor.
     * @property {module:model/CreateProjectStatusForProjectRequest}
     */
    CreateProjectStatusForProjectRequest,

    /**
     * The CreateStatusForObjectRequest model constructor.
     * @property {module:model/CreateStatusForObjectRequest}
     */
    CreateStatusForObjectRequest,

    /**
     * The CreateTag201Response model constructor.
     * @property {module:model/CreateTag201Response}
     */
    CreateTag201Response,

    /**
     * The CreateTagRequest model constructor.
     * @property {module:model/CreateTagRequest}
     */
    CreateTagRequest,

    /**
     * The CreateTask201Response model constructor.
     * @property {module:model/CreateTask201Response}
     */
    CreateTask201Response,

    /**
     * The CreateTaskRequest model constructor.
     * @property {module:model/CreateTaskRequest}
     */
    CreateTaskRequest,

    /**
     * The CreateTimeTrackingEntry201Response model constructor.
     * @property {module:model/CreateTimeTrackingEntry201Response}
     */
    CreateTimeTrackingEntry201Response,

    /**
     * The CreateTimeTrackingEntryRequest model constructor.
     * @property {module:model/CreateTimeTrackingEntryRequest}
     */
    CreateTimeTrackingEntryRequest,

    /**
     * The CreateWebhook201Response model constructor.
     * @property {module:model/CreateWebhook201Response}
     */
    CreateWebhook201Response,

    /**
     * The CreateWebhookRequest model constructor.
     * @property {module:model/CreateWebhookRequest}
     */
    CreateWebhookRequest,

    /**
     * The CustomFieldBase model constructor.
     * @property {module:model/CustomFieldBase}
     */
    CustomFieldBase,

    /**
     * The CustomFieldBaseDateValue model constructor.
     * @property {module:model/CustomFieldBaseDateValue}
     */
    CustomFieldBaseDateValue,

    /**
     * The CustomFieldBaseEnumOptionsInner model constructor.
     * @property {module:model/CustomFieldBaseEnumOptionsInner}
     */
    CustomFieldBaseEnumOptionsInner,

    /**
     * The CustomFieldBaseEnumValue model constructor.
     * @property {module:model/CustomFieldBaseEnumValue}
     */
    CustomFieldBaseEnumValue,

    /**
     * The CustomFieldCompact model constructor.
     * @property {module:model/CustomFieldCompact}
     */
    CustomFieldCompact,

    /**
     * The CustomFieldRequest model constructor.
     * @property {module:model/CustomFieldRequest}
     */
    CustomFieldRequest,

    /**
     * The CustomFieldResponse model constructor.
     * @property {module:model/CustomFieldResponse}
     */
    CustomFieldResponse,

    /**
     * The CustomFieldResponseCreatedBy model constructor.
     * @property {module:model/CustomFieldResponseCreatedBy}
     */
    CustomFieldResponseCreatedBy,

    /**
     * The CustomFieldResponsePeopleValueInner model constructor.
     * @property {module:model/CustomFieldResponsePeopleValueInner}
     */
    CustomFieldResponsePeopleValueInner,

    /**
     * The CustomFieldSettingBase model constructor.
     * @property {module:model/CustomFieldSettingBase}
     */
    CustomFieldSettingBase,

    /**
     * The CustomFieldSettingCompact model constructor.
     * @property {module:model/CustomFieldSettingCompact}
     */
    CustomFieldSettingCompact,

    /**
     * The CustomFieldSettingResponse model constructor.
     * @property {module:model/CustomFieldSettingResponse}
     */
    CustomFieldSettingResponse,

    /**
     * The CustomFieldSettingResponseCustomField model constructor.
     * @property {module:model/CustomFieldSettingResponseCustomField}
     */
    CustomFieldSettingResponseCustomField,

    /**
     * The CustomFieldSettingResponseParent model constructor.
     * @property {module:model/CustomFieldSettingResponseParent}
     */
    CustomFieldSettingResponseParent,

    /**
     * The CustomFieldSettingResponseProject model constructor.
     * @property {module:model/CustomFieldSettingResponseProject}
     */
    CustomFieldSettingResponseProject,

    /**
     * The DateVariableCompact model constructor.
     * @property {module:model/DateVariableCompact}
     */
    DateVariableCompact,

    /**
     * The DateVariableRequest model constructor.
     * @property {module:model/DateVariableRequest}
     */
    DateVariableRequest,

    /**
     * The DeleteAttachment200Response model constructor.
     * @property {module:model/DeleteAttachment200Response}
     */
    DeleteAttachment200Response,

    /**
     * The DuplicateProjectRequest model constructor.
     * @property {module:model/DuplicateProjectRequest}
     */
    DuplicateProjectRequest,

    /**
     * The DuplicateTaskRequest model constructor.
     * @property {module:model/DuplicateTaskRequest}
     */
    DuplicateTaskRequest,

    /**
     * The EnumOption model constructor.
     * @property {module:model/EnumOption}
     */
    EnumOption,

    /**
     * The EnumOptionBase model constructor.
     * @property {module:model/EnumOptionBase}
     */
    EnumOptionBase,

    /**
     * The EnumOptionInsertRequest model constructor.
     * @property {module:model/EnumOptionInsertRequest}
     */
    EnumOptionInsertRequest,

    /**
     * The EnumOptionRequest model constructor.
     * @property {module:model/EnumOptionRequest}
     */
    EnumOptionRequest,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ErrorResponseErrorsInner model constructor.
     * @property {module:model/ErrorResponseErrorsInner}
     */
    ErrorResponseErrorsInner,

    /**
     * The EventResponse model constructor.
     * @property {module:model/EventResponse}
     */
    EventResponse,

    /**
     * The EventResponseChange model constructor.
     * @property {module:model/EventResponseChange}
     */
    EventResponseChange,

    /**
     * The EventResponseParent model constructor.
     * @property {module:model/EventResponseParent}
     */
    EventResponseParent,

    /**
     * The EventResponseResource model constructor.
     * @property {module:model/EventResponseResource}
     */
    EventResponseResource,

    /**
     * The EventResponseUser model constructor.
     * @property {module:model/EventResponseUser}
     */
    EventResponseUser,

    /**
     * The GetAttachment200Response model constructor.
     * @property {module:model/GetAttachment200Response}
     */
    GetAttachment200Response,

    /**
     * The GetAttachmentsForObject200Response model constructor.
     * @property {module:model/GetAttachmentsForObject200Response}
     */
    GetAttachmentsForObject200Response,

    /**
     * The GetAuditLogEvents200Response model constructor.
     * @property {module:model/GetAuditLogEvents200Response}
     */
    GetAuditLogEvents200Response,

    /**
     * The GetCustomFieldSettingsForProject200Response model constructor.
     * @property {module:model/GetCustomFieldSettingsForProject200Response}
     */
    GetCustomFieldSettingsForProject200Response,

    /**
     * The GetCustomFieldsForWorkspace200Response model constructor.
     * @property {module:model/GetCustomFieldsForWorkspace200Response}
     */
    GetCustomFieldsForWorkspace200Response,

    /**
     * The GetEvents200Response model constructor.
     * @property {module:model/GetEvents200Response}
     */
    GetEvents200Response,

    /**
     * The GetFavoritesForUser200Response model constructor.
     * @property {module:model/GetFavoritesForUser200Response}
     */
    GetFavoritesForUser200Response,

    /**
     * The GetGoal200Response model constructor.
     * @property {module:model/GetGoal200Response}
     */
    GetGoal200Response,

    /**
     * The GetGoalRelationship200Response model constructor.
     * @property {module:model/GetGoalRelationship200Response}
     */
    GetGoalRelationship200Response,

    /**
     * The GetGoalRelationships200Response model constructor.
     * @property {module:model/GetGoalRelationships200Response}
     */
    GetGoalRelationships200Response,

    /**
     * The GetGoals200Response model constructor.
     * @property {module:model/GetGoals200Response}
     */
    GetGoals200Response,

    /**
     * The GetItemsForPortfolio200Response model constructor.
     * @property {module:model/GetItemsForPortfolio200Response}
     */
    GetItemsForPortfolio200Response,

    /**
     * The GetJob200Response model constructor.
     * @property {module:model/GetJob200Response}
     */
    GetJob200Response,

    /**
     * The GetMemberships200Response model constructor.
     * @property {module:model/GetMemberships200Response}
     */
    GetMemberships200Response,

    /**
     * The GetPortfolioMembership200Response model constructor.
     * @property {module:model/GetPortfolioMembership200Response}
     */
    GetPortfolioMembership200Response,

    /**
     * The GetPortfolioMemberships200Response model constructor.
     * @property {module:model/GetPortfolioMemberships200Response}
     */
    GetPortfolioMemberships200Response,

    /**
     * The GetPortfolios200Response model constructor.
     * @property {module:model/GetPortfolios200Response}
     */
    GetPortfolios200Response,

    /**
     * The GetProjectBrief200Response model constructor.
     * @property {module:model/GetProjectBrief200Response}
     */
    GetProjectBrief200Response,

    /**
     * The GetProjectMembership200Response model constructor.
     * @property {module:model/GetProjectMembership200Response}
     */
    GetProjectMembership200Response,

    /**
     * The GetProjectMembershipsForProject200Response model constructor.
     * @property {module:model/GetProjectMembershipsForProject200Response}
     */
    GetProjectMembershipsForProject200Response,

    /**
     * The GetProjectStatus200Response model constructor.
     * @property {module:model/GetProjectStatus200Response}
     */
    GetProjectStatus200Response,

    /**
     * The GetProjectStatusesForProject200Response model constructor.
     * @property {module:model/GetProjectStatusesForProject200Response}
     */
    GetProjectStatusesForProject200Response,

    /**
     * The GetProjectTemplate200Response model constructor.
     * @property {module:model/GetProjectTemplate200Response}
     */
    GetProjectTemplate200Response,

    /**
     * The GetProjectTemplates200Response model constructor.
     * @property {module:model/GetProjectTemplates200Response}
     */
    GetProjectTemplates200Response,

    /**
     * The GetSection200Response model constructor.
     * @property {module:model/GetSection200Response}
     */
    GetSection200Response,

    /**
     * The GetSectionsForProject200Response model constructor.
     * @property {module:model/GetSectionsForProject200Response}
     */
    GetSectionsForProject200Response,

    /**
     * The GetStatus200Response model constructor.
     * @property {module:model/GetStatus200Response}
     */
    GetStatus200Response,

    /**
     * The GetStatusesForObject200Response model constructor.
     * @property {module:model/GetStatusesForObject200Response}
     */
    GetStatusesForObject200Response,

    /**
     * The GetStoriesForTask200Response model constructor.
     * @property {module:model/GetStoriesForTask200Response}
     */
    GetStoriesForTask200Response,

    /**
     * The GetStory200Response model constructor.
     * @property {module:model/GetStory200Response}
     */
    GetStory200Response,

    /**
     * The GetTags200Response model constructor.
     * @property {module:model/GetTags200Response}
     */
    GetTags200Response,

    /**
     * The GetTaskCountsForProject200Response model constructor.
     * @property {module:model/GetTaskCountsForProject200Response}
     */
    GetTaskCountsForProject200Response,

    /**
     * The GetTasks200Response model constructor.
     * @property {module:model/GetTasks200Response}
     */
    GetTasks200Response,

    /**
     * The GetTeamMembership200Response model constructor.
     * @property {module:model/GetTeamMembership200Response}
     */
    GetTeamMembership200Response,

    /**
     * The GetTeamMemberships200Response model constructor.
     * @property {module:model/GetTeamMemberships200Response}
     */
    GetTeamMemberships200Response,

    /**
     * The GetTeamsForWorkspace200Response model constructor.
     * @property {module:model/GetTeamsForWorkspace200Response}
     */
    GetTeamsForWorkspace200Response,

    /**
     * The GetTimePeriod200Response model constructor.
     * @property {module:model/GetTimePeriod200Response}
     */
    GetTimePeriod200Response,

    /**
     * The GetTimePeriods200Response model constructor.
     * @property {module:model/GetTimePeriods200Response}
     */
    GetTimePeriods200Response,

    /**
     * The GetTimeTrackingEntriesForTask200Response model constructor.
     * @property {module:model/GetTimeTrackingEntriesForTask200Response}
     */
    GetTimeTrackingEntriesForTask200Response,

    /**
     * The GetUser200Response model constructor.
     * @property {module:model/GetUser200Response}
     */
    GetUser200Response,

    /**
     * The GetUserTaskList200Response model constructor.
     * @property {module:model/GetUserTaskList200Response}
     */
    GetUserTaskList200Response,

    /**
     * The GetUsers200Response model constructor.
     * @property {module:model/GetUsers200Response}
     */
    GetUsers200Response,

    /**
     * The GetWebhooks200Response model constructor.
     * @property {module:model/GetWebhooks200Response}
     */
    GetWebhooks200Response,

    /**
     * The GetWorkspace200Response model constructor.
     * @property {module:model/GetWorkspace200Response}
     */
    GetWorkspace200Response,

    /**
     * The GetWorkspaceMembership200Response model constructor.
     * @property {module:model/GetWorkspaceMembership200Response}
     */
    GetWorkspaceMembership200Response,

    /**
     * The GetWorkspaceMembershipsForUser200Response model constructor.
     * @property {module:model/GetWorkspaceMembershipsForUser200Response}
     */
    GetWorkspaceMembershipsForUser200Response,

    /**
     * The GetWorkspaces200Response model constructor.
     * @property {module:model/GetWorkspaces200Response}
     */
    GetWorkspaces200Response,

    /**
     * The GoalAddSubgoalRequest model constructor.
     * @property {module:model/GoalAddSubgoalRequest}
     */
    GoalAddSubgoalRequest,

    /**
     * The GoalAddSupportingRelationshipRequest model constructor.
     * @property {module:model/GoalAddSupportingRelationshipRequest}
     */
    GoalAddSupportingRelationshipRequest,

    /**
     * The GoalAddSupportingWorkRequest model constructor.
     * @property {module:model/GoalAddSupportingWorkRequest}
     */
    GoalAddSupportingWorkRequest,

    /**
     * The GoalBase model constructor.
     * @property {module:model/GoalBase}
     */
    GoalBase,

    /**
     * The GoalCompact model constructor.
     * @property {module:model/GoalCompact}
     */
    GoalCompact,

    /**
     * The GoalMembershipBase model constructor.
     * @property {module:model/GoalMembershipBase}
     */
    GoalMembershipBase,

    /**
     * The GoalMembershipBaseGoal model constructor.
     * @property {module:model/GoalMembershipBaseGoal}
     */
    GoalMembershipBaseGoal,

    /**
     * The GoalMembershipCompact model constructor.
     * @property {module:model/GoalMembershipCompact}
     */
    GoalMembershipCompact,

    /**
     * The GoalMembershipResponse model constructor.
     * @property {module:model/GoalMembershipResponse}
     */
    GoalMembershipResponse,

    /**
     * The GoalMetricBase model constructor.
     * @property {module:model/GoalMetricBase}
     */
    GoalMetricBase,

    /**
     * The GoalMetricCurrentValueRequest model constructor.
     * @property {module:model/GoalMetricCurrentValueRequest}
     */
    GoalMetricCurrentValueRequest,

    /**
     * The GoalMetricRequest model constructor.
     * @property {module:model/GoalMetricRequest}
     */
    GoalMetricRequest,

    /**
     * The GoalRelationshipBase model constructor.
     * @property {module:model/GoalRelationshipBase}
     */
    GoalRelationshipBase,

    /**
     * The GoalRelationshipBaseSupportedGoal model constructor.
     * @property {module:model/GoalRelationshipBaseSupportedGoal}
     */
    GoalRelationshipBaseSupportedGoal,

    /**
     * The GoalRelationshipBaseSupportingResource model constructor.
     * @property {module:model/GoalRelationshipBaseSupportingResource}
     */
    GoalRelationshipBaseSupportingResource,

    /**
     * The GoalRelationshipCompact model constructor.
     * @property {module:model/GoalRelationshipCompact}
     */
    GoalRelationshipCompact,

    /**
     * The GoalRelationshipRequest model constructor.
     * @property {module:model/GoalRelationshipRequest}
     */
    GoalRelationshipRequest,

    /**
     * The GoalRelationshipResponse model constructor.
     * @property {module:model/GoalRelationshipResponse}
     */
    GoalRelationshipResponse,

    /**
     * The GoalRemoveSubgoalRequest model constructor.
     * @property {module:model/GoalRemoveSubgoalRequest}
     */
    GoalRemoveSubgoalRequest,

    /**
     * The GoalRemoveSupportingRelationshipRequest model constructor.
     * @property {module:model/GoalRemoveSupportingRelationshipRequest}
     */
    GoalRemoveSupportingRelationshipRequest,

    /**
     * The GoalRequest model constructor.
     * @property {module:model/GoalRequest}
     */
    GoalRequest,

    /**
     * The GoalResponse model constructor.
     * @property {module:model/GoalResponse}
     */
    GoalResponse,

    /**
     * The GoalResponseCurrentStatusUpdate model constructor.
     * @property {module:model/GoalResponseCurrentStatusUpdate}
     */
    GoalResponseCurrentStatusUpdate,

    /**
     * The GoalResponseCurrentStatusUpdateAllOf model constructor.
     * @property {module:model/GoalResponseCurrentStatusUpdateAllOf}
     */
    GoalResponseCurrentStatusUpdateAllOf,

    /**
     * The GoalResponseLikesInner model constructor.
     * @property {module:model/GoalResponseLikesInner}
     */
    GoalResponseLikesInner,

    /**
     * The GoalResponseMetric model constructor.
     * @property {module:model/GoalResponseMetric}
     */
    GoalResponseMetric,

    /**
     * The GoalResponseTeam model constructor.
     * @property {module:model/GoalResponseTeam}
     */
    GoalResponseTeam,

    /**
     * The GoalResponseTeamAllOf model constructor.
     * @property {module:model/GoalResponseTeamAllOf}
     */
    GoalResponseTeamAllOf,

    /**
     * The GoalResponseTimePeriod model constructor.
     * @property {module:model/GoalResponseTimePeriod}
     */
    GoalResponseTimePeriod,

    /**
     * The GoalResponseWorkspace model constructor.
     * @property {module:model/GoalResponseWorkspace}
     */
    GoalResponseWorkspace,

    /**
     * The InsertEnumOptionForCustomFieldRequest model constructor.
     * @property {module:model/InsertEnumOptionForCustomFieldRequest}
     */
    InsertEnumOptionForCustomFieldRequest,

    /**
     * The InsertSectionForProjectRequest model constructor.
     * @property {module:model/InsertSectionForProjectRequest}
     */
    InsertSectionForProjectRequest,

    /**
     * The InstantiateProjectRequest model constructor.
     * @property {module:model/InstantiateProjectRequest}
     */
    InstantiateProjectRequest,

    /**
     * The JobBase model constructor.
     * @property {module:model/JobBase}
     */
    JobBase,

    /**
     * The JobBaseNewProject model constructor.
     * @property {module:model/JobBaseNewProject}
     */
    JobBaseNewProject,

    /**
     * The JobBaseNewProjectTemplate model constructor.
     * @property {module:model/JobBaseNewProjectTemplate}
     */
    JobBaseNewProjectTemplate,

    /**
     * The JobBaseNewTask model constructor.
     * @property {module:model/JobBaseNewTask}
     */
    JobBaseNewTask,

    /**
     * The JobBaseNewTaskTemplate model constructor.
     * @property {module:model/JobBaseNewTaskTemplate}
     */
    JobBaseNewTaskTemplate,

    /**
     * The JobBaseNewTaskTemplateAllOf model constructor.
     * @property {module:model/JobBaseNewTaskTemplateAllOf}
     */
    JobBaseNewTaskTemplateAllOf,

    /**
     * The JobCompact model constructor.
     * @property {module:model/JobCompact}
     */
    JobCompact,

    /**
     * The JobResponse model constructor.
     * @property {module:model/JobResponse}
     */
    JobResponse,

    /**
     * The Like model constructor.
     * @property {module:model/Like}
     */
    Like,

    /**
     * The MemberCompact model constructor.
     * @property {module:model/MemberCompact}
     */
    MemberCompact,

    /**
     * The MembershipRequest model constructor.
     * @property {module:model/MembershipRequest}
     */
    MembershipRequest,

    /**
     * The MembershipResponse model constructor.
     * @property {module:model/MembershipResponse}
     */
    MembershipResponse,

    /**
     * The MembershipResponseAnyOf model constructor.
     * @property {module:model/MembershipResponseAnyOf}
     */
    MembershipResponseAnyOf,

    /**
     * The MembershipResponseAnyOf1 model constructor.
     * @property {module:model/MembershipResponseAnyOf1}
     */
    MembershipResponseAnyOf1,

    /**
     * The MembershipResponseAnyOf2 model constructor.
     * @property {module:model/MembershipResponseAnyOf2}
     */
    MembershipResponseAnyOf2,

    /**
     * The MembershipResponseAnyOf3 model constructor.
     * @property {module:model/MembershipResponseAnyOf3}
     */
    MembershipResponseAnyOf3,

    /**
     * The MembershipResponseAnyOf4 model constructor.
     * @property {module:model/MembershipResponseAnyOf4}
     */
    MembershipResponseAnyOf4,

    /**
     * The MembershipResponseAnyOf4UserTaskList model constructor.
     * @property {module:model/MembershipResponseAnyOf4UserTaskList}
     */
    MembershipResponseAnyOf4UserTaskList,

    /**
     * The MessageBase model constructor.
     * @property {module:model/MessageBase}
     */
    MessageBase,

    /**
     * The MessageBaseAllOf model constructor.
     * @property {module:model/MessageBaseAllOf}
     */
    MessageBaseAllOf,

    /**
     * The MessageParent model constructor.
     * @property {module:model/MessageParent}
     */
    MessageParent,

    /**
     * The MessageParentAllOf model constructor.
     * @property {module:model/MessageParentAllOf}
     */
    MessageParentAllOf,

    /**
     * The ModifyDependenciesRequest model constructor.
     * @property {module:model/ModifyDependenciesRequest}
     */
    ModifyDependenciesRequest,

    /**
     * The ModifyDependentsRequest model constructor.
     * @property {module:model/ModifyDependentsRequest}
     */
    ModifyDependentsRequest,

    /**
     * The OrganizationExportBase model constructor.
     * @property {module:model/OrganizationExportBase}
     */
    OrganizationExportBase,

    /**
     * The OrganizationExportCompact model constructor.
     * @property {module:model/OrganizationExportCompact}
     */
    OrganizationExportCompact,

    /**
     * The OrganizationExportRequest model constructor.
     * @property {module:model/OrganizationExportRequest}
     */
    OrganizationExportRequest,

    /**
     * The OrganizationExportResponse model constructor.
     * @property {module:model/OrganizationExportResponse}
     */
    OrganizationExportResponse,

    /**
     * The PortfolioAddItemRequest model constructor.
     * @property {module:model/PortfolioAddItemRequest}
     */
    PortfolioAddItemRequest,

    /**
     * The PortfolioBase model constructor.
     * @property {module:model/PortfolioBase}
     */
    PortfolioBase,

    /**
     * The PortfolioCompact model constructor.
     * @property {module:model/PortfolioCompact}
     */
    PortfolioCompact,

    /**
     * The PortfolioMembershipBase model constructor.
     * @property {module:model/PortfolioMembershipBase}
     */
    PortfolioMembershipBase,

    /**
     * The PortfolioMembershipBasePortfolio model constructor.
     * @property {module:model/PortfolioMembershipBasePortfolio}
     */
    PortfolioMembershipBasePortfolio,

    /**
     * The PortfolioMembershipCompact model constructor.
     * @property {module:model/PortfolioMembershipCompact}
     */
    PortfolioMembershipCompact,

    /**
     * The PortfolioMembershipResponse model constructor.
     * @property {module:model/PortfolioMembershipResponse}
     */
    PortfolioMembershipResponse,

    /**
     * The PortfolioRemoveItemRequest model constructor.
     * @property {module:model/PortfolioRemoveItemRequest}
     */
    PortfolioRemoveItemRequest,

    /**
     * The PortfolioRequest model constructor.
     * @property {module:model/PortfolioRequest}
     */
    PortfolioRequest,

    /**
     * The PortfolioResponse model constructor.
     * @property {module:model/PortfolioResponse}
     */
    PortfolioResponse,

    /**
     * The PortfolioResponseCurrentStatusUpdate model constructor.
     * @property {module:model/PortfolioResponseCurrentStatusUpdate}
     */
    PortfolioResponseCurrentStatusUpdate,

    /**
     * The PortfolioResponseCustomFieldSettingsInner model constructor.
     * @property {module:model/PortfolioResponseCustomFieldSettingsInner}
     */
    PortfolioResponseCustomFieldSettingsInner,

    /**
     * The PortfolioResponseCustomFieldsInner model constructor.
     * @property {module:model/PortfolioResponseCustomFieldsInner}
     */
    PortfolioResponseCustomFieldsInner,

    /**
     * The PortfolioResponseWorkspace model constructor.
     * @property {module:model/PortfolioResponseWorkspace}
     */
    PortfolioResponseWorkspace,

    /**
     * The Preview model constructor.
     * @property {module:model/Preview}
     */
    Preview,

    /**
     * The ProjectBase model constructor.
     * @property {module:model/ProjectBase}
     */
    ProjectBase,

    /**
     * The ProjectBaseCurrentStatus model constructor.
     * @property {module:model/ProjectBaseCurrentStatus}
     */
    ProjectBaseCurrentStatus,

    /**
     * The ProjectBaseCurrentStatusAllOf model constructor.
     * @property {module:model/ProjectBaseCurrentStatusAllOf}
     */
    ProjectBaseCurrentStatusAllOf,

    /**
     * The ProjectBaseCurrentStatusUpdate model constructor.
     * @property {module:model/ProjectBaseCurrentStatusUpdate}
     */
    ProjectBaseCurrentStatusUpdate,

    /**
     * The ProjectBriefBase model constructor.
     * @property {module:model/ProjectBriefBase}
     */
    ProjectBriefBase,

    /**
     * The ProjectBriefCompact model constructor.
     * @property {module:model/ProjectBriefCompact}
     */
    ProjectBriefCompact,

    /**
     * The ProjectBriefRequest model constructor.
     * @property {module:model/ProjectBriefRequest}
     */
    ProjectBriefRequest,

    /**
     * The ProjectBriefResponse model constructor.
     * @property {module:model/ProjectBriefResponse}
     */
    ProjectBriefResponse,

    /**
     * The ProjectBriefResponseProject model constructor.
     * @property {module:model/ProjectBriefResponseProject}
     */
    ProjectBriefResponseProject,

    /**
     * The ProjectCompact model constructor.
     * @property {module:model/ProjectCompact}
     */
    ProjectCompact,

    /**
     * The ProjectDuplicateRequest model constructor.
     * @property {module:model/ProjectDuplicateRequest}
     */
    ProjectDuplicateRequest,

    /**
     * The ProjectDuplicateRequestScheduleDates model constructor.
     * @property {module:model/ProjectDuplicateRequestScheduleDates}
     */
    ProjectDuplicateRequestScheduleDates,

    /**
     * The ProjectMembershipBase model constructor.
     * @property {module:model/ProjectMembershipBase}
     */
    ProjectMembershipBase,

    /**
     * The ProjectMembershipCompact model constructor.
     * @property {module:model/ProjectMembershipCompact}
     */
    ProjectMembershipCompact,

    /**
     * The ProjectMembershipResponse model constructor.
     * @property {module:model/ProjectMembershipResponse}
     */
    ProjectMembershipResponse,

    /**
     * The ProjectMembershipResponseMember model constructor.
     * @property {module:model/ProjectMembershipResponseMember}
     */
    ProjectMembershipResponseMember,

    /**
     * The ProjectRequest model constructor.
     * @property {module:model/ProjectRequest}
     */
    ProjectRequest,

    /**
     * The ProjectResponse model constructor.
     * @property {module:model/ProjectResponse}
     */
    ProjectResponse,

    /**
     * The ProjectResponseCompletedBy model constructor.
     * @property {module:model/ProjectResponseCompletedBy}
     */
    ProjectResponseCompletedBy,

    /**
     * The ProjectResponseCreatedFromTemplate model constructor.
     * @property {module:model/ProjectResponseCreatedFromTemplate}
     */
    ProjectResponseCreatedFromTemplate,

    /**
     * The ProjectResponseOwner model constructor.
     * @property {module:model/ProjectResponseOwner}
     */
    ProjectResponseOwner,

    /**
     * The ProjectResponseProjectBrief model constructor.
     * @property {module:model/ProjectResponseProjectBrief}
     */
    ProjectResponseProjectBrief,

    /**
     * The ProjectResponseTeam model constructor.
     * @property {module:model/ProjectResponseTeam}
     */
    ProjectResponseTeam,

    /**
     * The ProjectSaveAsTemplateRequest model constructor.
     * @property {module:model/ProjectSaveAsTemplateRequest}
     */
    ProjectSaveAsTemplateRequest,

    /**
     * The ProjectSectionInsertRequest model constructor.
     * @property {module:model/ProjectSectionInsertRequest}
     */
    ProjectSectionInsertRequest,

    /**
     * The ProjectStatusBase model constructor.
     * @property {module:model/ProjectStatusBase}
     */
    ProjectStatusBase,

    /**
     * The ProjectStatusCompact model constructor.
     * @property {module:model/ProjectStatusCompact}
     */
    ProjectStatusCompact,

    /**
     * The ProjectStatusRequest model constructor.
     * @property {module:model/ProjectStatusRequest}
     */
    ProjectStatusRequest,

    /**
     * The ProjectStatusResponse model constructor.
     * @property {module:model/ProjectStatusResponse}
     */
    ProjectStatusResponse,

    /**
     * The ProjectTemplateBase model constructor.
     * @property {module:model/ProjectTemplateBase}
     */
    ProjectTemplateBase,

    /**
     * The ProjectTemplateBaseOwner model constructor.
     * @property {module:model/ProjectTemplateBaseOwner}
     */
    ProjectTemplateBaseOwner,

    /**
     * The ProjectTemplateBaseRequestedDatesInner model constructor.
     * @property {module:model/ProjectTemplateBaseRequestedDatesInner}
     */
    ProjectTemplateBaseRequestedDatesInner,

    /**
     * The ProjectTemplateBaseRequestedRolesInner model constructor.
     * @property {module:model/ProjectTemplateBaseRequestedRolesInner}
     */
    ProjectTemplateBaseRequestedRolesInner,

    /**
     * The ProjectTemplateCompact model constructor.
     * @property {module:model/ProjectTemplateCompact}
     */
    ProjectTemplateCompact,

    /**
     * The ProjectTemplateInstantiateProjectRequest model constructor.
     * @property {module:model/ProjectTemplateInstantiateProjectRequest}
     */
    ProjectTemplateInstantiateProjectRequest,

    /**
     * The ProjectTemplateInstantiateProjectRequestRequestedDatesInner model constructor.
     * @property {module:model/ProjectTemplateInstantiateProjectRequestRequestedDatesInner}
     */
    ProjectTemplateInstantiateProjectRequestRequestedDatesInner,

    /**
     * The ProjectTemplateInstantiateProjectRequestRequestedRolesInner model constructor.
     * @property {module:model/ProjectTemplateInstantiateProjectRequestRequestedRolesInner}
     */
    ProjectTemplateInstantiateProjectRequestRequestedRolesInner,

    /**
     * The ProjectTemplateResponse model constructor.
     * @property {module:model/ProjectTemplateResponse}
     */
    ProjectTemplateResponse,

    /**
     * The RemoveCustomFieldSettingForPortfolioRequest model constructor.
     * @property {module:model/RemoveCustomFieldSettingForPortfolioRequest}
     */
    RemoveCustomFieldSettingForPortfolioRequest,

    /**
     * The RemoveCustomFieldSettingRequest model constructor.
     * @property {module:model/RemoveCustomFieldSettingRequest}
     */
    RemoveCustomFieldSettingRequest,

    /**
     * The RemoveFollowerForTaskRequest model constructor.
     * @property {module:model/RemoveFollowerForTaskRequest}
     */
    RemoveFollowerForTaskRequest,

    /**
     * The RemoveFollowersForProjectRequest model constructor.
     * @property {module:model/RemoveFollowersForProjectRequest}
     */
    RemoveFollowersForProjectRequest,

    /**
     * The RemoveFollowersRequest model constructor.
     * @property {module:model/RemoveFollowersRequest}
     */
    RemoveFollowersRequest,

    /**
     * The RemoveItemForPortfolioRequest model constructor.
     * @property {module:model/RemoveItemForPortfolioRequest}
     */
    RemoveItemForPortfolioRequest,

    /**
     * The RemoveMembersForPortfolioRequest model constructor.
     * @property {module:model/RemoveMembersForPortfolioRequest}
     */
    RemoveMembersForPortfolioRequest,

    /**
     * The RemoveMembersRequest model constructor.
     * @property {module:model/RemoveMembersRequest}
     */
    RemoveMembersRequest,

    /**
     * The RemoveProjectForTaskRequest model constructor.
     * @property {module:model/RemoveProjectForTaskRequest}
     */
    RemoveProjectForTaskRequest,

    /**
     * The RemoveSupportingRelationshipRequest model constructor.
     * @property {module:model/RemoveSupportingRelationshipRequest}
     */
    RemoveSupportingRelationshipRequest,

    /**
     * The RemoveTagForTaskRequest model constructor.
     * @property {module:model/RemoveTagForTaskRequest}
     */
    RemoveTagForTaskRequest,

    /**
     * The RemoveUserForTeamRequest model constructor.
     * @property {module:model/RemoveUserForTeamRequest}
     */
    RemoveUserForTeamRequest,

    /**
     * The RemoveUserForWorkspaceRequest model constructor.
     * @property {module:model/RemoveUserForWorkspaceRequest}
     */
    RemoveUserForWorkspaceRequest,

    /**
     * The RequestedRoleRequest model constructor.
     * @property {module:model/RequestedRoleRequest}
     */
    RequestedRoleRequest,

    /**
     * The RuleTriggerRequest model constructor.
     * @property {module:model/RuleTriggerRequest}
     */
    RuleTriggerRequest,

    /**
     * The RuleTriggerResponse model constructor.
     * @property {module:model/RuleTriggerResponse}
     */
    RuleTriggerResponse,

    /**
     * The ScimUser model constructor.
     * @property {module:model/ScimUser}
     */
    ScimUser,

    /**
     * The SectionBase model constructor.
     * @property {module:model/SectionBase}
     */
    SectionBase,

    /**
     * The SectionCompact model constructor.
     * @property {module:model/SectionCompact}
     */
    SectionCompact,

    /**
     * The SectionRequest model constructor.
     * @property {module:model/SectionRequest}
     */
    SectionRequest,

    /**
     * The SectionResponse model constructor.
     * @property {module:model/SectionResponse}
     */
    SectionResponse,

    /**
     * The SectionTaskInsertRequest model constructor.
     * @property {module:model/SectionTaskInsertRequest}
     */
    SectionTaskInsertRequest,

    /**
     * The SetParentForTaskRequest model constructor.
     * @property {module:model/SetParentForTaskRequest}
     */
    SetParentForTaskRequest,

    /**
     * The StatusUpdateBase model constructor.
     * @property {module:model/StatusUpdateBase}
     */
    StatusUpdateBase,

    /**
     * The StatusUpdateCompact model constructor.
     * @property {module:model/StatusUpdateCompact}
     */
    StatusUpdateCompact,

    /**
     * The StatusUpdateRequest model constructor.
     * @property {module:model/StatusUpdateRequest}
     */
    StatusUpdateRequest,

    /**
     * The StatusUpdateResponse model constructor.
     * @property {module:model/StatusUpdateResponse}
     */
    StatusUpdateResponse,

    /**
     * The StatusUpdateResponseParent model constructor.
     * @property {module:model/StatusUpdateResponseParent}
     */
    StatusUpdateResponseParent,

    /**
     * The StoryBase model constructor.
     * @property {module:model/StoryBase}
     */
    StoryBase,

    /**
     * The StoryCompact model constructor.
     * @property {module:model/StoryCompact}
     */
    StoryCompact,

    /**
     * The StoryRequest model constructor.
     * @property {module:model/StoryRequest}
     */
    StoryRequest,

    /**
     * The StoryResponse model constructor.
     * @property {module:model/StoryResponse}
     */
    StoryResponse,

    /**
     * The StoryResponseAssignee model constructor.
     * @property {module:model/StoryResponseAssignee}
     */
    StoryResponseAssignee,

    /**
     * The StoryResponseCustomField model constructor.
     * @property {module:model/StoryResponseCustomField}
     */
    StoryResponseCustomField,

    /**
     * The StoryResponseDates model constructor.
     * @property {module:model/StoryResponseDates}
     */
    StoryResponseDates,

    /**
     * The StoryResponseNewDateValue model constructor.
     * @property {module:model/StoryResponseNewDateValue}
     */
    StoryResponseNewDateValue,

    /**
     * The StoryResponseOldDateValue model constructor.
     * @property {module:model/StoryResponseOldDateValue}
     */
    StoryResponseOldDateValue,

    /**
     * The StoryResponseOldDates model constructor.
     * @property {module:model/StoryResponseOldDates}
     */
    StoryResponseOldDates,

    /**
     * The StoryResponseOldEnumValue model constructor.
     * @property {module:model/StoryResponseOldEnumValue}
     */
    StoryResponseOldEnumValue,

    /**
     * The StoryResponseOldSection model constructor.
     * @property {module:model/StoryResponseOldSection}
     */
    StoryResponseOldSection,

    /**
     * The StoryResponsePreviewsInner model constructor.
     * @property {module:model/StoryResponsePreviewsInner}
     */
    StoryResponsePreviewsInner,

    /**
     * The StoryResponseProject model constructor.
     * @property {module:model/StoryResponseProject}
     */
    StoryResponseProject,

    /**
     * The StoryResponseStory model constructor.
     * @property {module:model/StoryResponseStory}
     */
    StoryResponseStory,

    /**
     * The StoryResponseTag model constructor.
     * @property {module:model/StoryResponseTag}
     */
    StoryResponseTag,

    /**
     * The StoryResponseTarget model constructor.
     * @property {module:model/StoryResponseTarget}
     */
    StoryResponseTarget,

    /**
     * The StoryResponseTask model constructor.
     * @property {module:model/StoryResponseTask}
     */
    StoryResponseTask,

    /**
     * The TagBase model constructor.
     * @property {module:model/TagBase}
     */
    TagBase,

    /**
     * The TagCompact model constructor.
     * @property {module:model/TagCompact}
     */
    TagCompact,

    /**
     * The TagRequest model constructor.
     * @property {module:model/TagRequest}
     */
    TagRequest,

    /**
     * The TagResponse model constructor.
     * @property {module:model/TagResponse}
     */
    TagResponse,

    /**
     * The TaskAddFollowersRequest model constructor.
     * @property {module:model/TaskAddFollowersRequest}
     */
    TaskAddFollowersRequest,

    /**
     * The TaskAddProjectRequest model constructor.
     * @property {module:model/TaskAddProjectRequest}
     */
    TaskAddProjectRequest,

    /**
     * The TaskAddTagRequest model constructor.
     * @property {module:model/TaskAddTagRequest}
     */
    TaskAddTagRequest,

    /**
     * The TaskBase model constructor.
     * @property {module:model/TaskBase}
     */
    TaskBase,

    /**
     * The TaskBaseExternal model constructor.
     * @property {module:model/TaskBaseExternal}
     */
    TaskBaseExternal,

    /**
     * The TaskBaseMembershipsInner model constructor.
     * @property {module:model/TaskBaseMembershipsInner}
     */
    TaskBaseMembershipsInner,

    /**
     * The TaskBaseMembershipsInnerSection model constructor.
     * @property {module:model/TaskBaseMembershipsInnerSection}
     */
    TaskBaseMembershipsInnerSection,

    /**
     * The TaskCompact model constructor.
     * @property {module:model/TaskCompact}
     */
    TaskCompact,

    /**
     * The TaskConvertToTemplateRequest model constructor.
     * @property {module:model/TaskConvertToTemplateRequest}
     */
    TaskConvertToTemplateRequest,

    /**
     * The TaskCountResponse model constructor.
     * @property {module:model/TaskCountResponse}
     */
    TaskCountResponse,

    /**
     * The TaskDuplicateRequest model constructor.
     * @property {module:model/TaskDuplicateRequest}
     */
    TaskDuplicateRequest,

    /**
     * The TaskRemoveFollowersRequest model constructor.
     * @property {module:model/TaskRemoveFollowersRequest}
     */
    TaskRemoveFollowersRequest,

    /**
     * The TaskRemoveProjectRequest model constructor.
     * @property {module:model/TaskRemoveProjectRequest}
     */
    TaskRemoveProjectRequest,

    /**
     * The TaskRemoveTagRequest model constructor.
     * @property {module:model/TaskRemoveTagRequest}
     */
    TaskRemoveTagRequest,

    /**
     * The TaskRequest model constructor.
     * @property {module:model/TaskRequest}
     */
    TaskRequest,

    /**
     * The TaskResponse model constructor.
     * @property {module:model/TaskResponse}
     */
    TaskResponse,

    /**
     * The TaskResponseAssignee model constructor.
     * @property {module:model/TaskResponseAssignee}
     */
    TaskResponseAssignee,

    /**
     * The TaskResponseAssigneeSection model constructor.
     * @property {module:model/TaskResponseAssigneeSection}
     */
    TaskResponseAssigneeSection,

    /**
     * The TaskResponseCustomFieldsInner model constructor.
     * @property {module:model/TaskResponseCustomFieldsInner}
     */
    TaskResponseCustomFieldsInner,

    /**
     * The TaskResponseParent model constructor.
     * @property {module:model/TaskResponseParent}
     */
    TaskResponseParent,

    /**
     * The TaskResponseTagsInner model constructor.
     * @property {module:model/TaskResponseTagsInner}
     */
    TaskResponseTagsInner,

    /**
     * The TaskResponseWorkspace model constructor.
     * @property {module:model/TaskResponseWorkspace}
     */
    TaskResponseWorkspace,

    /**
     * The TaskSetParentRequest model constructor.
     * @property {module:model/TaskSetParentRequest}
     */
    TaskSetParentRequest,

    /**
     * The TaskTemplateCompact model constructor.
     * @property {module:model/TaskTemplateCompact}
     */
    TaskTemplateCompact,

    /**
     * The TaskTemplateInstantiateTaskRequest model constructor.
     * @property {module:model/TaskTemplateInstantiateTaskRequest}
     */
    TaskTemplateInstantiateTaskRequest,

    /**
     * The TeamAddUserRequest model constructor.
     * @property {module:model/TeamAddUserRequest}
     */
    TeamAddUserRequest,

    /**
     * The TeamBase model constructor.
     * @property {module:model/TeamBase}
     */
    TeamBase,

    /**
     * The TeamCompact model constructor.
     * @property {module:model/TeamCompact}
     */
    TeamCompact,

    /**
     * The TeamMembershipBase model constructor.
     * @property {module:model/TeamMembershipBase}
     */
    TeamMembershipBase,

    /**
     * The TeamMembershipCompact model constructor.
     * @property {module:model/TeamMembershipCompact}
     */
    TeamMembershipCompact,

    /**
     * The TeamMembershipResponse model constructor.
     * @property {module:model/TeamMembershipResponse}
     */
    TeamMembershipResponse,

    /**
     * The TeamRemoveUserRequest model constructor.
     * @property {module:model/TeamRemoveUserRequest}
     */
    TeamRemoveUserRequest,

    /**
     * The TeamRequest model constructor.
     * @property {module:model/TeamRequest}
     */
    TeamRequest,

    /**
     * The TeamResponse model constructor.
     * @property {module:model/TeamResponse}
     */
    TeamResponse,

    /**
     * The TeamResponseOrganization model constructor.
     * @property {module:model/TeamResponseOrganization}
     */
    TeamResponseOrganization,

    /**
     * The TemplateRole model constructor.
     * @property {module:model/TemplateRole}
     */
    TemplateRole,

    /**
     * The TimePeriodBase model constructor.
     * @property {module:model/TimePeriodBase}
     */
    TimePeriodBase,

    /**
     * The TimePeriodBaseParent model constructor.
     * @property {module:model/TimePeriodBaseParent}
     */
    TimePeriodBaseParent,

    /**
     * The TimePeriodCompact model constructor.
     * @property {module:model/TimePeriodCompact}
     */
    TimePeriodCompact,

    /**
     * The TimePeriodResponse model constructor.
     * @property {module:model/TimePeriodResponse}
     */
    TimePeriodResponse,

    /**
     * The TimeTrackingEntryBase model constructor.
     * @property {module:model/TimeTrackingEntryBase}
     */
    TimeTrackingEntryBase,

    /**
     * The TimeTrackingEntryCompact model constructor.
     * @property {module:model/TimeTrackingEntryCompact}
     */
    TimeTrackingEntryCompact,

    /**
     * The TriggerRule200Response model constructor.
     * @property {module:model/TriggerRule200Response}
     */
    TriggerRule200Response,

    /**
     * The TriggerRuleRequest model constructor.
     * @property {module:model/TriggerRuleRequest}
     */
    TriggerRuleRequest,

    /**
     * The TypeaheadForWorkspace200Response model constructor.
     * @property {module:model/TypeaheadForWorkspace200Response}
     */
    TypeaheadForWorkspace200Response,

    /**
     * The UpdateGoalMetricRequest model constructor.
     * @property {module:model/UpdateGoalMetricRequest}
     */
    UpdateGoalMetricRequest,

    /**
     * The UpdateGoalRelationshipRequest model constructor.
     * @property {module:model/UpdateGoalRelationshipRequest}
     */
    UpdateGoalRelationshipRequest,

    /**
     * The UpdateGoalRequest model constructor.
     * @property {module:model/UpdateGoalRequest}
     */
    UpdateGoalRequest,

    /**
     * The UpdateMembershipRequest model constructor.
     * @property {module:model/UpdateMembershipRequest}
     */
    UpdateMembershipRequest,

    /**
     * The UpdateProjectBriefRequest model constructor.
     * @property {module:model/UpdateProjectBriefRequest}
     */
    UpdateProjectBriefRequest,

    /**
     * The UpdateSectionRequest model constructor.
     * @property {module:model/UpdateSectionRequest}
     */
    UpdateSectionRequest,

    /**
     * The UpdateStoryRequest model constructor.
     * @property {module:model/UpdateStoryRequest}
     */
    UpdateStoryRequest,

    /**
     * The UpdateTeam200Response model constructor.
     * @property {module:model/UpdateTeam200Response}
     */
    UpdateTeam200Response,

    /**
     * The UpdateTeamRequest model constructor.
     * @property {module:model/UpdateTeamRequest}
     */
    UpdateTeamRequest,

    /**
     * The UpdateTimeTrackingEntryRequest model constructor.
     * @property {module:model/UpdateTimeTrackingEntryRequest}
     */
    UpdateTimeTrackingEntryRequest,

    /**
     * The UpdateWebhookRequest model constructor.
     * @property {module:model/UpdateWebhookRequest}
     */
    UpdateWebhookRequest,

    /**
     * The UpdateWorkspaceRequest model constructor.
     * @property {module:model/UpdateWorkspaceRequest}
     */
    UpdateWorkspaceRequest,

    /**
     * The UserBase model constructor.
     * @property {module:model/UserBase}
     */
    UserBase,

    /**
     * The UserBaseResponse model constructor.
     * @property {module:model/UserBaseResponse}
     */
    UserBaseResponse,

    /**
     * The UserBaseResponsePhoto model constructor.
     * @property {module:model/UserBaseResponsePhoto}
     */
    UserBaseResponsePhoto,

    /**
     * The UserCompact model constructor.
     * @property {module:model/UserCompact}
     */
    UserCompact,

    /**
     * The UserRequest model constructor.
     * @property {module:model/UserRequest}
     */
    UserRequest,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
     * The UserTaskListBase model constructor.
     * @property {module:model/UserTaskListBase}
     */
    UserTaskListBase,

    /**
     * The UserTaskListBaseOwner model constructor.
     * @property {module:model/UserTaskListBaseOwner}
     */
    UserTaskListBaseOwner,

    /**
     * The UserTaskListBaseWorkspace model constructor.
     * @property {module:model/UserTaskListBaseWorkspace}
     */
    UserTaskListBaseWorkspace,

    /**
     * The UserTaskListCompact model constructor.
     * @property {module:model/UserTaskListCompact}
     */
    UserTaskListCompact,

    /**
     * The UserTaskListRequest model constructor.
     * @property {module:model/UserTaskListRequest}
     */
    UserTaskListRequest,

    /**
     * The UserTaskListResponse model constructor.
     * @property {module:model/UserTaskListResponse}
     */
    UserTaskListResponse,

    /**
     * The WebhookCompact model constructor.
     * @property {module:model/WebhookCompact}
     */
    WebhookCompact,

    /**
     * The WebhookFilter model constructor.
     * @property {module:model/WebhookFilter}
     */
    WebhookFilter,

    /**
     * The WebhookRequest model constructor.
     * @property {module:model/WebhookRequest}
     */
    WebhookRequest,

    /**
     * The WebhookRequestFiltersInner model constructor.
     * @property {module:model/WebhookRequestFiltersInner}
     */
    WebhookRequestFiltersInner,

    /**
     * The WebhookResponse model constructor.
     * @property {module:model/WebhookResponse}
     */
    WebhookResponse,

    /**
     * The WebhookUpdateRequest model constructor.
     * @property {module:model/WebhookUpdateRequest}
     */
    WebhookUpdateRequest,

    /**
     * The WorkspaceAddUserRequest model constructor.
     * @property {module:model/WorkspaceAddUserRequest}
     */
    WorkspaceAddUserRequest,

    /**
     * The WorkspaceBase model constructor.
     * @property {module:model/WorkspaceBase}
     */
    WorkspaceBase,

    /**
     * The WorkspaceCompact model constructor.
     * @property {module:model/WorkspaceCompact}
     */
    WorkspaceCompact,

    /**
     * The WorkspaceEventResponse model constructor.
     * @property {module:model/WorkspaceEventResponse}
     */
    WorkspaceEventResponse,

    /**
     * The WorkspaceEventResponseAllOf model constructor.
     * @property {module:model/WorkspaceEventResponseAllOf}
     */
    WorkspaceEventResponseAllOf,

    /**
     * The WorkspaceMembershipBase model constructor.
     * @property {module:model/WorkspaceMembershipBase}
     */
    WorkspaceMembershipBase,

    /**
     * The WorkspaceMembershipCompact model constructor.
     * @property {module:model/WorkspaceMembershipCompact}
     */
    WorkspaceMembershipCompact,

    /**
     * The WorkspaceMembershipRequest model constructor.
     * @property {module:model/WorkspaceMembershipRequest}
     */
    WorkspaceMembershipRequest,

    /**
     * The WorkspaceMembershipResponse model constructor.
     * @property {module:model/WorkspaceMembershipResponse}
     */
    WorkspaceMembershipResponse,

    /**
     * The WorkspaceMembershipResponseUserTaskList model constructor.
     * @property {module:model/WorkspaceMembershipResponseUserTaskList}
     */
    WorkspaceMembershipResponseUserTaskList,

    /**
     * The WorkspaceMembershipResponseVacationDates model constructor.
     * @property {module:model/WorkspaceMembershipResponseVacationDates}
     */
    WorkspaceMembershipResponseVacationDates,

    /**
     * The WorkspaceRemoveUserRequest model constructor.
     * @property {module:model/WorkspaceRemoveUserRequest}
     */
    WorkspaceRemoveUserRequest,

    /**
     * The WorkspaceRequest model constructor.
     * @property {module:model/WorkspaceRequest}
     */
    WorkspaceRequest,

    /**
     * The WorkspaceResponse model constructor.
     * @property {module:model/WorkspaceResponse}
     */
    WorkspaceResponse,

    /**
    * The AttachmentsApi service constructor.
    * @property {module:api/AttachmentsApi}
    */
    AttachmentsApi,

    /**
    * The AuditLogAPIApi service constructor.
    * @property {module:api/AuditLogAPIApi}
    */
    AuditLogAPIApi,

    /**
    * The BatchAPIApi service constructor.
    * @property {module:api/BatchAPIApi}
    */
    BatchAPIApi,

    /**
    * The CustomFieldSettingsApi service constructor.
    * @property {module:api/CustomFieldSettingsApi}
    */
    CustomFieldSettingsApi,

    /**
    * The CustomFieldsApi service constructor.
    * @property {module:api/CustomFieldsApi}
    */
    CustomFieldsApi,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The GoalRelationshipsApi service constructor.
    * @property {module:api/GoalRelationshipsApi}
    */
    GoalRelationshipsApi,

    /**
    * The GoalsApi service constructor.
    * @property {module:api/GoalsApi}
    */
    GoalsApi,

    /**
    * The JobsApi service constructor.
    * @property {module:api/JobsApi}
    */
    JobsApi,

    /**
    * The MembershipsApi service constructor.
    * @property {module:api/MembershipsApi}
    */
    MembershipsApi,

    /**
    * The OrganizationExportsApi service constructor.
    * @property {module:api/OrganizationExportsApi}
    */
    OrganizationExportsApi,

    /**
    * The PortfolioMembershipsApi service constructor.
    * @property {module:api/PortfolioMembershipsApi}
    */
    PortfolioMembershipsApi,

    /**
    * The PortfoliosApi service constructor.
    * @property {module:api/PortfoliosApi}
    */
    PortfoliosApi,

    /**
    * The ProjectBriefsApi service constructor.
    * @property {module:api/ProjectBriefsApi}
    */
    ProjectBriefsApi,

    /**
    * The ProjectMembershipsApi service constructor.
    * @property {module:api/ProjectMembershipsApi}
    */
    ProjectMembershipsApi,

    /**
    * The ProjectStatusesApi service constructor.
    * @property {module:api/ProjectStatusesApi}
    */
    ProjectStatusesApi,

    /**
    * The ProjectTemplatesApi service constructor.
    * @property {module:api/ProjectTemplatesApi}
    */
    ProjectTemplatesApi,

    /**
    * The ProjectsApi service constructor.
    * @property {module:api/ProjectsApi}
    */
    ProjectsApi,

    /**
    * The RulesApi service constructor.
    * @property {module:api/RulesApi}
    */
    RulesApi,

    /**
    * The SectionsApi service constructor.
    * @property {module:api/SectionsApi}
    */
    SectionsApi,

    /**
    * The StatusUpdatesApi service constructor.
    * @property {module:api/StatusUpdatesApi}
    */
    StatusUpdatesApi,

    /**
    * The StoriesApi service constructor.
    * @property {module:api/StoriesApi}
    */
    StoriesApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
    * The TasksApi service constructor.
    * @property {module:api/TasksApi}
    */
    TasksApi,

    /**
    * The TeamMembershipsApi service constructor.
    * @property {module:api/TeamMembershipsApi}
    */
    TeamMembershipsApi,

    /**
    * The TeamsApi service constructor.
    * @property {module:api/TeamsApi}
    */
    TeamsApi,

    /**
    * The TimePeriodsApi service constructor.
    * @property {module:api/TimePeriodsApi}
    */
    TimePeriodsApi,

    /**
    * The TimeTrackingEntriesApi service constructor.
    * @property {module:api/TimeTrackingEntriesApi}
    */
    TimeTrackingEntriesApi,

    /**
    * The TypeaheadApi service constructor.
    * @property {module:api/TypeaheadApi}
    */
    TypeaheadApi,

    /**
    * The UserTaskListsApi service constructor.
    * @property {module:api/UserTaskListsApi}
    */
    UserTaskListsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WebhooksApi service constructor.
    * @property {module:api/WebhooksApi}
    */
    WebhooksApi,

    /**
    * The WorkspaceMembershipsApi service constructor.
    * @property {module:api/WorkspaceMembershipsApi}
    */
    WorkspaceMembershipsApi,

    /**
    * The WorkspacesApi service constructor.
    * @property {module:api/WorkspacesApi}
    */
    WorkspacesApi
};
